// packages/zui/src/svelte/AppShellHeader.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { appShellHeaderVariants } from '../shared/appShellVariants'
import { useAppShellContext } from './appShellContext'

type Props = HTMLAttributes<HTMLElement> & {
  toggle?: boolean
  toggleLabel?: string
  class?: string
  children?: Snippet
}

let {
  toggle = true,
  toggleLabel = 'Toggle sidebar',
  class: className,
  children,
  ...rest
}: Props = $props()

const ctx = useAppShellContext('AppShellHeader')
const classes = $derived(appShellHeaderVariants({ class: className }))
</script>

<header class={classes} {...rest}>
  {#if toggle}
    <button
      type="button"
      class="zui-app-shell-toggle"
      aria-label={toggleLabel}
      aria-controls={ctx.sidebarId}
      onclick={ctx.toggle}
    >
      <i class="ph ph-list" aria-hidden="true"></i>
    </button>
  {/if}
  {@render children?.()}
</header>

// packages/zui/src/vue/AppShellHeader.vue
<template>
  <header :class="classes" v-bind="$attrs">
    <button
      v-if="toggle"
      type="button"
      class="zui-app-shell-toggle"
      :aria-label="toggleLabel"
      :aria-controls="ctx.sidebarId"
      @click="ctx.toggle"
    >
      <i class="ph ph-list" aria-hidden="true" />
    </button>
    <slot />
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { appShellHeaderVariants } from '../shared/appShellVariants'
import { useAppShellContext } from './appShellContext'

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    class?: string
    toggle?: boolean
    toggleLabel?: string
  }>(),
  { toggle: true, toggleLabel: 'Toggle sidebar' },
)

const ctx = useAppShellContext('AppShellHeader')
const classes = computed(() => appShellHeaderVariants({ class: props.class }))
</script>
