// packages/zui/src/svelte/Card.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLAnchorAttributes, HTMLAttributes } from 'svelte/elements'
import { cardVariants } from '../shared/cardVariants'

type CardVariantProps = VariantProps<typeof cardVariants>

type Props = (HTMLAttributes<HTMLDivElement> & HTMLAnchorAttributes) & {
  class?: string
  href?: string
  shape?: CardVariantProps['shape']
  children?: Snippet
}

let { class: className, href, shape, children, ...rest }: Props = $props()

const classes = $derived(
  cardVariants({
    className: [href && 'zui-card-interactive', className]
      .filter(Boolean)
      .join(' '),
    shape,
  }),
)
</script>

{#if href}
  <a class={classes} {href} {...rest}>
    {@render children?.()}
  </a>
{:else}
  <div class={classes} {...rest}>
    {@render children?.()}
  </div>
{/if}

// packages/zui/src/vue/Card.vue
<template>
  <a v-if="href" :class="classes" :href="href" v-bind="$attrs">
    <slot />
  </a>
  <div v-else :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { cardVariants } from '../shared/cardVariants'

defineOptions({ inheritAttrs: false })

type CardVariantProps = VariantProps<typeof cardVariants>

const props = defineProps<{
  class?: string
  href?: string
  shape?: CardVariantProps['shape']
}>()

const classes = computed(() =>
  cardVariants({
    className: [props.href && 'zui-card-interactive', props.class]
      .filter(Boolean)
      .join(' '),
    shape: props.shape,
  }),
)
</script>
