// packages/zui/src/react/CardTitle.tsx
import type { HTMLAttributes } from 'react'

export type CardTitleProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardTitle({ className, children, ...props }: CardTitleProps) {
  const classes = ['zui-card-title', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/vue/CardTitle.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-card-title', props.class].filter(Boolean).join(' '),
)
</script>
