// src/react/CollapsibleTrigger.tsx
import type { HTMLAttributes } from 'react'

export type CollapsibleTriggerProps = HTMLAttributes<HTMLElement>

export function CollapsibleTrigger({
  className,
  ...props
}: CollapsibleTriggerProps) {
  const classes = ['zui-collapsible-trigger', className]
    .filter(Boolean)
    .join(' ')
  return <summary className={classes} {...props} />
}

// packages/zui/src/vue/CollapsibleTrigger.vue
<template>
  <summary :class="classes" v-bind="$attrs">
    <slot />
  </summary>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-collapsible-trigger', props.class].filter(Boolean).join(' '),
)
</script>
