// packages/zui/src/react/Collapsible.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { collapsibleVariants } from '../shared/collapsibleVariants'

type CollapsibleVariantProps = VariantProps<typeof collapsibleVariants>

export type CollapsibleProps = HTMLAttributes<HTMLDetailsElement> &
  CollapsibleVariantProps & {
    open?: boolean
  }

export function Collapsible({ className, shape, ...props }: CollapsibleProps) {
  const classes = collapsibleVariants({ className, shape })
  return <details className={classes} {...props} />
}

// packages/zui/src/vue/Collapsible.vue
<template>
  <details :class="classes" v-bind="$attrs">
    <slot />
  </details>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { collapsibleVariants } from '../shared/collapsibleVariants'

defineOptions({ inheritAttrs: false })

type CollapsibleVariantProps = VariantProps<typeof collapsibleVariants>

const props = defineProps<{
  class?: string
  shape?: CollapsibleVariantProps['shape']
}>()

const classes = computed(() =>
  collapsibleVariants({ className: props.class, shape: props.shape }),
)
</script>
