// src/react/DialogFooter.tsx
import type { HTMLAttributes } from 'react'

export type DialogFooterProps = HTMLAttributes<HTMLDivElement>

export function DialogFooter({ className, children, ...props }: DialogFooterProps) {
  return (
    <div className={['zui-dialog-footer', className].filter(Boolean).join(' ')} {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/vue/DialogFooter.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-dialog-footer', props.class].filter(Boolean).join(' '),
)
</script>
