// packages/zui/src/react/Field.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { fieldVariants } from '../shared/fieldVariants'

type FieldVariantProps = VariantProps<typeof fieldVariants>

export type FieldProps = HTMLAttributes<HTMLDivElement> &
  FieldVariantProps & {
    className?: string
  }

export function Field({
  className,
  orientation,
  invalid,
  children,
  ...props
}: FieldProps) {
  const classes = fieldVariants({
    className,
    invalid,
    orientation,
  })
  return (
    <div className={classes} role="group" {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/vue/Field.vue
<template>
  <div role="group" :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { fieldVariants } from '../shared/fieldVariants'

defineOptions({ inheritAttrs: false })

type FieldVariantProps = VariantProps<typeof fieldVariants>

const props = defineProps<{
  class?: string
  orientation?: FieldVariantProps['orientation']
  invalid?: FieldVariantProps['invalid']
}>()

const classes = computed(() =>
  fieldVariants({
    className: props.class,
    invalid: props.invalid,
    orientation: props.orientation,
  }),
)
</script>
