// packages/zui/src/react/FieldError.tsx
import type { HTMLAttributes } from 'react'

export type FieldErrorProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldError({ className, children, ...props }: FieldErrorProps) {
  const classes = ['zui-field-error', className].filter(Boolean).join(' ')
  return (
    <div className={classes} role="alert" {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/vue/FieldError.vue
<template>
  <div role="alert" :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-field-error', props.class].filter(Boolean).join(' '),
)
</script>
