// packages/zui/src/react/FieldSeparator.tsx
import type { HTMLAttributes } from 'react'

export type FieldSeparatorProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldSeparator({
  className,
  children,
  ...props
}: FieldSeparatorProps) {
  const classes = ['zui-field-separator', className].filter(Boolean).join(' ')
  return (
    <div className={classes} role="separator" {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/vue/FieldSeparator.vue
<template>
  <div role="separator" :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-field-separator', props.class].filter(Boolean).join(' '),
)
</script>
