// packages/zui/src/react/Input.tsx
import type { VariantProps } from 'cva'
import type { InputHTMLAttributes } from 'react'
import { inputVariants } from '../shared/inputVariants'

type InputVariantProps = VariantProps<typeof inputVariants>

export type InputProps = InputHTMLAttributes<HTMLInputElement> &
  InputVariantProps & {
    className?: string
  }

export function Input({ className, shape, ...props }: InputProps) {
  const classes = inputVariants({ className, shape })
  return <input className={classes} {...props} />
}

// packages/zui/src/vue/Input.vue
<template>
  <input :class="classes" v-bind="$attrs" />
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { inputVariants } from '../shared/inputVariants'

defineOptions({ inheritAttrs: false })

type InputVariantProps = VariantProps<typeof inputVariants>

const props = defineProps<{
  class?: string
  shape?: InputVariantProps['shape']
}>()

const classes = computed(() =>
  inputVariants({ className: props.class, shape: props.shape }),
)
</script>
