// packages/zui/src/react/MenuContent.tsx
import type { HTMLAttributes } from 'react'
import { useEffect, useRef } from 'react'
import { useMenuContext, useMenuSnapshot } from './menuContext'

export type MenuContentProps = HTMLAttributes<HTMLDivElement>

export function MenuContent({ className, onKeyDown, ...props }: MenuContentProps) {
  const ref = useRef<HTMLDivElement>(null)
  const { controller } = useMenuContext()
  const snapshot = useMenuSnapshot()

  useEffect(() => {
    return controller.registerContent({
      contentId: snapshot.contentId,
      element: ref.current,
    })
  }, [controller, snapshot.contentId])

  return (
    <div
      {...props}
      ref={ref}
      aria-labelledby={snapshot.triggerId}
      className={['zui-menu-content', className].filter(Boolean).join(' ')}
      data-align={snapshot.align}
      data-side={snapshot.side}
      data-state={snapshot.open ? 'open' : 'closed'}
      data-zui-menu-content=""
      hidden={!snapshot.open}
      id={snapshot.contentId}
      onKeyDown={(event) => {
        onKeyDown?.(event)
        if (!event.defaultPrevented) controller.handleContentKeydown(event.nativeEvent)
      }}
      role="menu"
    />
  )
}

// packages/zui/src/vue/MenuContent.vue
<template>
  <div
    v-bind="$attrs"
    ref="contentRef"
    :aria-labelledby="snapshot.triggerId"
    :class="classes"
    :data-align="snapshot.align"
    :data-side="snapshot.side"
    :data-state="snapshot.open ? 'open' : 'closed'"
    data-zui-menu-content=""
    :hidden="!snapshot.open"
    :id="snapshot.contentId"
    role="menu"
    @keydown="handleKeydown"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, onUnmounted, ref, watchEffect } from 'vue'
import { useMenuContext } from './menuContext'

defineOptions({ inheritAttrs: false })

const props = defineProps<{ class?: string }>()
const { controller, snapshot } = useMenuContext()
const contentRef = ref<HTMLDivElement>()
let unregister = () => {}

watchEffect(() => {
  unregister()
  unregister = controller.registerContent({
    contentId: snapshot.value.contentId,
    element: contentRef.value ?? null,
  })
})

onUnmounted(() => unregister())

const classes = computed(() => ['zui-menu-content', props.class].filter(Boolean).join(' '))

function handleKeydown(event: KeyboardEvent) {
  if (!event.defaultPrevented) controller.handleContentKeydown(event)
}
</script>
