// packages/zui/src/svelte/Menu.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { createMenuController, type MenuAlign, type MenuDirection, type MenuSide } from '../core/menu'
import { setMenuContext } from './menuContext'

type Props = HTMLAttributes<HTMLDivElement> & {
  align?: MenuAlign
  defaultOpen?: boolean
  dir?: MenuDirection
  disabled?: boolean
  id?: string
  modal?: boolean
  onOpenChange?: (open: boolean) => void
  open?: boolean
  side?: MenuSide
  class?: string
  children?: Snippet
}

let {
  align,
  class: className,
  defaultOpen,
  dir,
  disabled,
  id,
  modal,
  onOpenChange,
  open,
  side,
  children,
  ...rest
}: Props = $props()

let root = $state<HTMLDivElement | undefined>()
const controller = createMenuController({ align, defaultOpen, dir, disabled, id, modal, onOpenChange, open, side })
let snapshot = $state(controller.getSnapshot())

const unsubscribe = controller.subscribe((next) => {
  snapshot = next
})

$effect(() => {
  controller.setOptions({ align, defaultOpen, dir, disabled, id, modal, onOpenChange, open, side })
})

$effect(() => {
  const onPointerDown = (event: PointerEvent) => controller.handleDocumentPointerDown(event.target)
  document.addEventListener('pointerdown', onPointerDown)
  return () => document.removeEventListener('pointerdown', onPointerDown)
})

$effect(() => unsubscribe)

setMenuContext({
  controller,
  getRoot: () => root,
  getSnapshot: () => snapshot,
})
</script>

<div
  {...rest}
  bind:this={root}
  class={['zui-menu', className].filter(Boolean).join(' ')}
  data-align={snapshot.align}
  data-disabled={snapshot.disabled ? 'true' : undefined}
  data-side={snapshot.side}
  data-state={snapshot.open ? 'open' : 'closed'}
  data-zui-menu-root=""
  id={snapshot.rootId}
>
  {@render children?.()}
</div>

// packages/zui/src/vue/Menu.vue
<template>
  <div
    v-bind="$attrs"
    ref="rootRef"
    :class="classes"
    :data-align="snapshot.align"
    :data-disabled="snapshot.disabled ? 'true' : undefined"
    :data-side="snapshot.side"
    :data-state="snapshot.open ? 'open' : 'closed'"
    data-zui-menu-root=""
    :id="snapshot.rootId"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, onUnmounted, ref, watchEffect } from 'vue'
import { createMenuController, type MenuAlign, type MenuDirection, type MenuSide } from '../core/menu'
import { provideMenuContext } from './menuContext'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  align?: MenuAlign
  class?: string
  defaultOpen?: boolean
  dir?: MenuDirection
  disabled?: boolean
  id?: string
  modal?: boolean
  onOpenChange?: (open: boolean) => void
  open?: boolean
  side?: MenuSide
}>()

const controller = createMenuController({
  align: props.align,
  defaultOpen: props.defaultOpen,
  dir: props.dir,
  disabled: props.disabled,
  id: props.id,
  modal: props.modal,
  onOpenChange: props.onOpenChange,
  open: props.open,
  side: props.side,
})

const rootRef = ref<HTMLDivElement>()
const snapshot = ref(controller.getSnapshot())
const unsubscribe = controller.subscribe((next) => {
  snapshot.value = next
})

watchEffect(() => {
  controller.setOptions({
    align: props.align,
    defaultOpen: props.defaultOpen,
    dir: props.dir,
    disabled: props.disabled,
    id: props.id,
    modal: props.modal,
    onOpenChange: props.onOpenChange,
    open: props.open,
    side: props.side,
  })
})

const onPointerDown = (event: PointerEvent) => controller.handleDocumentPointerDown(event.target)
document.addEventListener('pointerdown', onPointerDown)

onUnmounted(() => {
  unsubscribe()
  document.removeEventListener('pointerdown', onPointerDown)
})

provideMenuContext({ controller, rootRef, snapshot })

const classes = computed(() => ['zui-menu', props.class].filter(Boolean).join(' '))
</script>
