// packages/zui/src/react/TableRow.tsx
import type { HTMLAttributes } from 'react'

export type TableRowProps = HTMLAttributes<HTMLTableRowElement> & {
  className?: string
}

export function TableRow({ className, children, ...props }: TableRowProps) {
  const classes = ['zui-table-row', className].filter(Boolean).join(' ')
  return (
    <tr className={classes} {...props}>
      {children}
    </tr>
  )
}

// packages/zui/src/vue/TableRow.vue
<template>
  <tr :class="classes" v-bind="$attrs">
    <slot />
  </tr>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-table-row', props.class].filter(Boolean).join(' '),
)
</script>
