// packages/zui/src/react/TableHeader.tsx
import type { HTMLAttributes } from 'react'

export type TableHeaderProps = HTMLAttributes<HTMLTableSectionElement> & {
  className?: string
}

export function TableHeader({
  className,
  children,
  ...props
}: TableHeaderProps) {
  const classes = ['zui-table-header', className].filter(Boolean).join(' ')
  return (
    <thead className={classes} {...props}>
      {children}
    </thead>
  )
}

// packages/zui/src/vue/TableHeader.vue
<template>
  <thead :class="classes" v-bind="$attrs">
    <slot />
  </thead>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-table-header', props.class].filter(Boolean).join(' '),
)
</script>
