// packages/zui/src/svelte/Textarea.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { HTMLTextareaAttributes } from 'svelte/elements'
import { textareaVariants } from '../shared/textareaVariants'

type TextareaVariantProps = VariantProps<typeof textareaVariants>

type Props = HTMLTextareaAttributes & {
  class?: string
  shape?: TextareaVariantProps['shape']
  value?: string | null
}

let { class: className, shape, value = $bindable(), ...rest }: Props = $props()

const classes = $derived(textareaVariants({ className, shape }))
</script>

<textarea class={classes} bind:value {...rest}></textarea>

// packages/zui/src/vue/Textarea.vue
<template>
  <textarea :class="classes" v-bind="$attrs" />
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { textareaVariants } from '../shared/textareaVariants'

defineOptions({ inheritAttrs: false })

type TextareaVariantProps = VariantProps<typeof textareaVariants>

const props = defineProps<{
  class?: string
  shape?: TextareaVariantProps['shape']
}>()

const classes = computed(() =>
  textareaVariants({ className: props.class, shape: props.shape }),
)
</script>
