// src/react/Avatar.tsx
import { useState } from 'react'
import type { HTMLAttributes } from 'react'
import type { VariantProps } from 'cva'
import { avatarVariants } from '../shared/avatarVariants'

type AvatarVariantProps = VariantProps<typeof avatarVariants>

export interface AvatarProps extends HTMLAttributes<HTMLSpanElement>, AvatarVariantProps {
  src?: string
  alt?: string
  fallback?: React.ReactNode
  className?: string
}

export function Avatar({ className, size, shape, src, alt, fallback, ...props }: AvatarProps) {
  const [imageError, setImageError] = useState(false)
  const classes = avatarVariants({ size, shape, className })

  return (
    <span className={classes} {...props}>
      <span className="zui-avatar-fallback">
        {fallback ?? <i className="ph ph-user" aria-hidden="true" />}
      </span>
      {src && !imageError && (
        <img
          className="zui-avatar-image"
          src={src}
          alt={alt ?? ''}
          onError={() => setImageError(true)}
        />
      )}
    </span>
  )
}

// src/svelte/Avatar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import type { VariantProps } from 'cva'
  import { avatarVariants } from '../shared/avatarVariants'

  type AvatarVariantProps = VariantProps<typeof avatarVariants>

  type Props = HTMLAttributes<HTMLSpanElement> & {
    class?: string
    src?: string
    alt?: string
    size?: AvatarVariantProps['size']
    shape?: AvatarVariantProps['shape']
    fallback?: Snippet
  }

  let {
    class: className,
    src,
    alt,
    size,
    shape,
    fallback,
    ...rest
  }: Props = $props()

  let imageError = $state(false)
  const classes = $derived(avatarVariants({ size, shape, className }))
</script>

<span class={classes} {...rest}>
  <span class="zui-avatar-fallback">
    {#if fallback}
      {@render fallback()}
    {:else}
      <i class="ph ph-user" aria-hidden="true"></i>
    {/if}
  </span>
  {#if src && !imageError}
    <img
      class="zui-avatar-image"
      {src}
      alt={alt ?? ''}
      onerror={() => (imageError = true)}
    />
  {/if}
</span>
