// src/react/CardHeader.tsx
import type { HTMLAttributes } from 'react'

export type CardHeaderProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardHeader({ className, children, ...props }: CardHeaderProps) {
  const classes = ['zui-card-header', className].filter(Boolean).join(' ')
  return <div className={classes} {...props}>{children}</div>
}

// src/svelte/CardHeader.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-card-header', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>
