// src/react/CardDescription.tsx
import type { HTMLAttributes } from 'react'

export type CardDescriptionProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardDescription({ className, children, ...props }: CardDescriptionProps) {
  const classes = ['zui-card-description', className].filter(Boolean).join(' ')
  return <div className={classes} {...props}>{children}</div>
}

// src/svelte/CardDescription.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDivElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-card-description', className].filter(Boolean).join(' '),
  )
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>
