// src/react/Code.tsx
import type { HTMLAttributes } from 'react'

export type CodeProps = HTMLAttributes<HTMLElement> & {
  className?: string
}

export function Code({ className, children, ...props }: CodeProps) {
  const classes = ['zui-code', className].filter(Boolean).join(' ')
  return (
    <code className={classes} {...props}>
      {children}
    </code>
  )
}

// src/svelte/Code.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(['zui-code', className].filter(Boolean).join(' '))
</script>

<code class={classes} {...rest}>
  {@render children?.()}
</code>
