// packages/zui/src/solid/DialogTitle.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type DialogTitleProps = JSX.HTMLAttributes<HTMLHeadingElement>

export function DialogTitle(props: DialogTitleProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-dialog-title', local.class].filter(Boolean).join(' ')
  return (
    <h2 class={classes()} {...rest}>
      {local.children}
    </h2>
  )
}

// src/svelte/DialogTitle.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLHeadingElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-dialog-title', className].filter(Boolean).join(' '),
)
</script>

<h2 class={classes} {...rest}>
  {@render children?.()}
</h2>
