// packages/zui/src/react/Prose.tsx
import type { HTMLAttributes } from 'react'

export type ProseProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function Prose({ className, children, ...props }: ProseProps) {
  const classes = ['prose', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}

// src/svelte/Prose.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDivElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(['prose', className].filter(Boolean).join(' '))
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>
