// packages/zui/src/react/TableFooter.tsx
import type { HTMLAttributes } from 'react'

export type TableFooterProps = HTMLAttributes<HTMLTableSectionElement> & {
  className?: string
}

export function TableFooter({
  className,
  children,
  ...props
}: TableFooterProps) {
  const classes = ['zui-table-footer', className].filter(Boolean).join(' ')
  return (
    <tfoot className={classes} {...props}>
      {children}
    </tfoot>
  )
}

// src/svelte/TableFooter.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLTableSectionElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-table-footer', className].filter(Boolean).join(' '),
)
</script>

<tfoot class={classes} {...rest}>
  {@render children?.()}
</tfoot>
