// packages/zui/src/react/TableHeader.tsx
import type { HTMLAttributes } from 'react'

export type TableHeaderProps = HTMLAttributes<HTMLTableSectionElement> & {
  className?: string
}

export function TableHeader({
  className,
  children,
  ...props
}: TableHeaderProps) {
  const classes = ['zui-table-header', className].filter(Boolean).join(' ')
  return (
    <thead className={classes} {...props}>
      {children}
    </thead>
  )
}

// src/svelte/TableHeader.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLTableSectionElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-table-header', className].filter(Boolean).join(' '),
)
</script>

<thead class={classes} {...rest}>
  {@render children?.()}
</thead>
