// src/vue/Textarea.vue
<template>
  <textarea :class="classes" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-textarea', props.class].filter(Boolean).join(' '),
)
</script>

// src/svelte/Textarea.svelte
<script lang="ts">
  import type { HTMLTextareaAttributes } from 'svelte/elements'

  type Props = HTMLTextareaAttributes & {
    class?: string
    value?: string | null
  }

  let {
    class: className,
    value = $bindable(),
    ...rest
  }: Props = $props()

  const classes = $derived(
    ['zui-textarea', className].filter(Boolean).join(' '),
  )
</script>

<textarea class={classes} bind:value {...rest}></textarea>
