// src/vue/Tooltip.vue
<template>
  <span :class="['zui-tooltip', props.class].filter(Boolean).join(' ')" v-bind="$attrs">
    <span
      :style="{ 'anchor-name': anchorName }"
      @mouseenter="show"
      @mouseleave="hide"
      @focus="show"
      @blur="hide"
    >
      <slot />
    </span>
    <span
      popover="manual"
      :id="id"
      ref="popoverEl"
      :class="contentClass"
      role="tooltip"
      :style="{ 'position-anchor': anchorName }"
    >
      {{ text }}
    </span>
  </span>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import type { VariantProps } from 'cva'
import { tooltipVariants } from '../shared/tooltipVariants'

defineOptions({ inheritAttrs: false })

let counter = 0
const id = `tooltip-${++counter}-${Math.random().toString(36).slice(2, 7)}`
const anchorName = `--${id}`
const popoverEl = ref<HTMLElement | null>(null)

type TooltipVariantProps = VariantProps<typeof tooltipVariants>

const props = defineProps<{
  text: string
  class?: string
  placement?: TooltipVariantProps['placement']
}>()

const contentClass = computed(() => {
  const placementClass = tooltipVariants({ placement: props.placement }).split(' ').find((c: string) => c.startsWith('zui-tooltip-placement-'))
  return ['zui-tooltip-content', placementClass].filter(Boolean).join(' ')
})

const show = () => (popoverEl.value as any)?.showPopover()
const hide = () => (popoverEl.value as any)?.hidePopover()
</script>

// src/svelte/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import type { VariantProps } from 'cva'
  import { tooltipVariants } from '../shared/tooltipVariants'

  type TooltipVariantProps = VariantProps<typeof tooltipVariants>

  type Props = HTMLAttributes<HTMLSpanElement> & {
    text: string
    class?: string
    placement?: TooltipVariantProps['placement']
    children?: Snippet
  }

  let {
    text,
    class: className,
    placement,
    children,
    ...rest
  }: Props = $props()

  const id = `tooltip-${Math.random().toString(36).slice(2, 9)}`
  const anchorName = `--${id}`
  let popoverEl = $state<HTMLSpanElement | null>(null)

  const contentClass = $derived(
    [
      'zui-tooltip-content',
      tooltipVariants({ placement })
        .split(' ')
        .find((c: string) => c.startsWith('zui-tooltip-placement-')),
    ]
      .filter(Boolean)
      .join(' '),
  )

  const wrapperClass = $derived(
    ['zui-tooltip', className].filter(Boolean).join(' '),
  )

  const show = () => popoverEl?.showPopover()
  const hide = () => popoverEl?.hidePopover()
</script>

<span class={wrapperClass} {...rest}>
  <span
    style="anchor-name: {anchorName};"
    onmouseenter={show}
    onmouseleave={hide}
    onfocusin={show}
    onfocusout={hide}
  >
    {@render children?.()}
  </span>
  <span
    bind:this={popoverEl}
    popover="manual"
    {id}
    class={contentClass}
    role="tooltip"
    style="position-anchor: {anchorName};"
  >
    {text}
  </span>
</span>
