// packages/zui/src/react/AccordionItem.tsx
import type { HTMLAttributes } from 'react'

export type AccordionItemProps = HTMLAttributes<HTMLDetailsElement> & {
  open?: boolean
  name?: string
}

export function AccordionItem({ className, ...props }: AccordionItemProps) {
  const classes = ['zui-accordion-item', className].filter(Boolean).join(' ')
  return <details className={classes} {...props} />
}

// src/solid/AccordionItem.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type AccordionItemProps = JSX.DetailsHtmlAttributes<HTMLDetailsElement> & {
	open?: boolean
	name?: string
}

export function AccordionItem(props: AccordionItemProps) {
	const [local, rest] = splitProps(props, ['class'])
	const classes = () =>
		['zui-accordion-item', local.class].filter(Boolean).join(' ')
	return <details class={classes()} {...rest} />
}
