// packages/zui/src/react/Accordion.tsx
import type { HTMLAttributes } from 'react'

export type AccordionProps = HTMLAttributes<HTMLDivElement> & {
  flush?: boolean
}

export function Accordion({ className, flush, ...props }: AccordionProps) {
  const classes = ['zui-accordion', flush && 'zui-accordion-flush', className]
    .filter(Boolean)
    .join(' ')
  return <div className={classes} {...props} />
}

// src/solid/Accordion.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type AccordionProps = JSX.HTMLAttributes<HTMLDivElement> & {
	flush?: boolean
}

export function Accordion(props: AccordionProps) {
	const [local, rest] = splitProps(props, ['class', 'flush'])
	const classes = () =>
		['zui-accordion', local.flush && 'zui-accordion-flush', local.class]
			.filter(Boolean)
			.join(' ')
	return <div class={classes()} {...rest} />
}
