// src/react/Button.tsx
import type { VariantProps } from 'cva'
import type { AnchorHTMLAttributes, ButtonHTMLAttributes } from 'react'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

type ButtonBaseProps = ButtonVariantProps & {
  className?: string
}

type ButtonAsButton = ButtonBaseProps &
  ButtonHTMLAttributes<HTMLButtonElement> & {
    href?: never
  }

type ButtonAsAnchor = ButtonBaseProps &
  AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
  }

export type ButtonProps = ButtonAsButton | ButtonAsAnchor

export function Button({
  className,
  variant,
  color,
  size,
  shape,
  icon,
  ...props
}: ButtonProps) {
  const classes = buttonVariants({
    className,
    color,
    icon,
    shape,
    size,
    variant,
  })

  if ('href' in props && props.href) {
    return (
      <a
        className={classes}
        {...(props as AnchorHTMLAttributes<HTMLAnchorElement>)}
      />
    )
  }

  return (
    <button
      className={classes}
      {...(props as ButtonHTMLAttributes<HTMLButtonElement>)}
    />
  )
}

// src/solid/Button.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import type { VariantProps } from 'cva'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type ButtonProps = ButtonVariantProps &
	JSX.ButtonHTMLAttributes<HTMLButtonElement> &
	JSX.AnchorHTMLAttributes<HTMLAnchorElement> & {
		class?: string
		href?: string
	}

export function Button(props: ButtonProps) {
	const [local, rest] = splitProps(props, [
		'class',
		'variant',
		'color',
		'size',
		'shape',
		'icon',
		'href',
	])
	const classes = () =>
		buttonVariants({
			variant: local.variant,
			color: local.color,
			size: local.size,
			shape: local.shape,
			icon: local.icon,
			className: local.class,
		})

	return (
		<>
			{local.href ? (
				<a
					class={classes()}
					href={local.href}
					{...(rest as JSX.AnchorHTMLAttributes<HTMLAnchorElement>)}
				/>
			) : (
				<button
					class={classes()}
					{...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
				/>
			)}
		</>
	)
}
