// src/react/CardHeader.tsx
import type { HTMLAttributes } from 'react'

export type CardHeaderProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardHeader({ className, children, ...props }: CardHeaderProps) {
  const classes = ['zui-card-header', className].filter(Boolean).join(' ')
  return <div className={classes} {...props}>{children}</div>
}

// src/solid/CardHeader.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type CardHeaderProps = JSX.HTMLAttributes<HTMLDivElement> & {
	class?: string
}

export function CardHeader(props: CardHeaderProps) {
	const [local, rest] = splitProps(props, ['class', 'children'])
	const classes = () => ['zui-card-header', local.class].filter(Boolean).join(' ')
	return (
		<div class={classes()} {...rest}>
			{local.children}
		</div>
	)
}
