// src/react/Input.tsx
import type { InputHTMLAttributes } from 'react'

export type InputProps = InputHTMLAttributes<HTMLInputElement> & {
  className?: string
}

export function Input({ className, ...props }: InputProps) {
  const classes = ['zui-input', className].filter(Boolean).join(' ')
  return <input className={classes} {...props} />
}

// src/solid/Input.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type InputProps = JSX.InputHTMLAttributes<HTMLInputElement> & {
	class?: string
}

export function Input(props: InputProps) {
	const [local, rest] = splitProps(props, ['class'])
	const classes = () => ['zui-input', local.class].filter(Boolean).join(' ')
	return <input class={classes()} {...rest} />
}
