// src/react/Label.tsx
import type { LabelHTMLAttributes } from 'react'

export type LabelProps = LabelHTMLAttributes<HTMLLabelElement> & {
  className?: string
}

export function Label({ className, children, ...props }: LabelProps) {
  const classes = ['zui-label', className].filter(Boolean).join(' ')
  return <label className={classes} {...props}>{children}</label>
}

// src/solid/Label.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type LabelProps = JSX.LabelHTMLAttributes<HTMLLabelElement> & {
  class?: string
}

export function Label(props: LabelProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-label', local.class].filter(Boolean).join(' ')
  return (
    <label class={classes()} {...rest}>
      {local.children}
    </label>
  )
}
