// packages/zui/src/react/Popover.tsx
import type { CSSProperties, HTMLAttributes } from 'react'

export type PopoverProps = HTMLAttributes<HTMLDivElement> & {
  id: string
  popover?: 'auto' | 'manual'
}

export function Popover({
  id,
  popover = 'auto',
  className,
  style,
  children,
  ...props
}: PopoverProps) {
  const classes = ['zui-popover', className].filter(Boolean).join(' ')
  const anchorStyle: CSSProperties = {
    positionAnchor: `--${id}`,
    ...style,
  }

  return (
    <div
      id={id}
      popover={popover}
      className={classes}
      style={anchorStyle}
      {...props}
    >
      {children}
    </div>
  )
}

// src/solid/Popover.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type PopoverProps = JSX.HTMLAttributes<HTMLDivElement> & {
	id: string
	popover?: 'auto' | 'manual'
}

export function Popover(props: PopoverProps) {
	const [local, rest] = splitProps(props, [
		'id',
		'popover',
		'class',
		'style',
		'children',
	])
	const classes = () => ['zui-popover', local.class].filter(Boolean).join(' ')
	const anchorStyle = (): JSX.CSSProperties => ({
		'position-anchor': `--${local.id}`,
		...(typeof local.style === 'object' ? local.style : {}),
	})

	return (
		<div
			id={local.id}
			popover={local.popover ?? 'auto'}
			class={classes()}
			style={anchorStyle()}
			{...rest}
		>
			{local.children}
		</div>
	)
}
