// packages/zui/src/react/Radio.tsx
import type { InputHTMLAttributes } from 'react'

export type RadioProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> & {
  className?: string
}

export function Radio({ className, children, ...props }: RadioProps) {
  const classes = ['zui-radio', className].filter(Boolean).join(' ')
  return (
    <label className={classes}>
      <input type="radio" {...props} />
      {children}
    </label>
  )
}

// src/solid/Radio.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type RadioProps = Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'type'> & {
	class?: string
}

export function Radio(props: RadioProps) {
	const [local, rest] = splitProps(props, ['class', 'children'])
	const classes = () => ['zui-radio', local.class].filter(Boolean).join(' ')
	return (
		<label class={classes()}>
			<input type="radio" {...rest} />
			{local.children}
		</label>
	)
}
