// src/react/TableRow.tsx
import type { HTMLAttributes } from 'react'

export type TableRowProps = HTMLAttributes<HTMLTableRowElement> & {
  className?: string
}

export function TableRow({ className, children, ...props }: TableRowProps) {
  const classes = ['zui-table-row', className].filter(Boolean).join(' ')
  return <tr className={classes} {...props}>{children}</tr>
}

// src/solid/TableRow.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TableRowProps = JSX.HTMLAttributes<HTMLTableRowElement> & {
  class?: string
}

export function TableRow(props: TableRowProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-table-row', local.class].filter(Boolean).join(' ')
  return (
    <tr class={classes()} {...rest}>
      {local.children}
    </tr>
  )
}
