// src/react/TableBody.tsx
import type { HTMLAttributes } from 'react'

export type TableBodyProps = HTMLAttributes<HTMLTableSectionElement> & {
  className?: string
}

export function TableBody({ className, children, ...props }: TableBodyProps) {
  const classes = ['zui-table-body', className].filter(Boolean).join(' ')
  return (
    <tbody className={classes} {...props}>
      {children}
    </tbody>
  )
}

// src/solid/TableBody.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TableBodyProps = JSX.HTMLAttributes<HTMLTableSectionElement> & {
  class?: string
}

export function TableBody(props: TableBodyProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-table-body', local.class].filter(Boolean).join(' ')
  return (
    <tbody class={classes()} {...rest}>
      {local.children}
    </tbody>
  )
}
