// packages/zui/src/react/TableFooter.tsx
import type { HTMLAttributes } from 'react'

export type TableFooterProps = HTMLAttributes<HTMLTableSectionElement> & {
  className?: string
}

export function TableFooter({
  className,
  children,
  ...props
}: TableFooterProps) {
  const classes = ['zui-table-footer', className].filter(Boolean).join(' ')
  return (
    <tfoot className={classes} {...props}>
      {children}
    </tfoot>
  )
}

// src/solid/TableFooter.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TableFooterProps = JSX.HTMLAttributes<HTMLTableSectionElement> & {
	class?: string
}

export function TableFooter(props: TableFooterProps) {
	const [local, rest] = splitProps(props, ['class', 'children'])
	const classes = () => ['zui-table-footer', local.class].filter(Boolean).join(' ')
	return (
		<tfoot class={classes()} {...rest}>
			{local.children}
		</tfoot>
	)
}
