// src/react/TableCaption.tsx
import type { HTMLAttributes } from 'react'

export type TableCaptionProps = HTMLAttributes<HTMLTableCaptionElement> & {
  className?: string
}

export function TableCaption({
  className,
  children,
  ...props
}: TableCaptionProps) {
  const classes = ['zui-table-caption', className].filter(Boolean).join(' ')
  return (
    <caption className={classes} {...props}>
      {children}
    </caption>
  )
}

// src/solid/TableCaption.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TableCaptionProps = JSX.HTMLAttributes<HTMLTableCaptionElement> & {
	class?: string
}

export function TableCaption(props: TableCaptionProps) {
	const [local, rest] = splitProps(props, ['class', 'children'])
	const classes = () => ['zui-table-caption', local.class].filter(Boolean).join(' ')
	return (
		<caption class={classes()} {...rest}>
			{local.children}
		</caption>
	)
}
