// packages/zui/src/vue/AppShellMain.vue
<template>
  <main v-bind="$attrs" :id="id ?? ctx.mainId" :class="classes">
    <slot />
  </main>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { appShellMainVariants } from '../shared/appShellVariants'
import { useAppShellContext } from './appShellContext'

defineOptions({ inheritAttrs: false })
const props = defineProps<{ id?: string; class?: string }>()
const ctx = useAppShellContext('AppShellMain')
const classes = computed(() => appShellMainVariants({ class: props.class }))
</script>

// packages/zui/src/svelte/AppShellMain.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { appShellMainVariants } from '../shared/appShellVariants'
import { useAppShellContext } from './appShellContext'

type Props = HTMLAttributes<HTMLElement> & {
  class?: string
  children?: Snippet
}

let { class: className, id, children, ...rest }: Props = $props()
const ctx = useAppShellContext('AppShellMain')
const classes = $derived(appShellMainVariants({ class: className }))
</script>

<main id={id ?? ctx.mainId} class={classes} {...rest}>
  {@render children?.()}
</main>
