// packages/zui/src/vue/AppShellSidebar.vue
<template>
  <aside
    ref="el"
    :id="ctx.sidebarId"
    :class="classes"
    :aria-label="label"
    popover="auto"
    v-bind="$attrs"
  >
    <slot />
  </aside>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { appShellSidebarVariants } from '../shared/appShellVariants'
import { useAppShellContext } from './appShellContext'

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    class?: string
    label?: string
  }>(),
  { label: 'Sidebar' },
)

const ctx = useAppShellContext('AppShellSidebar')
const el = ref<HTMLElement | null>(null)
const classes = computed(() => appShellSidebarVariants({ class: props.class }))

onMounted(() => {
  if (el.value) ctx.setSidebar(el.value)
})
</script>

// packages/zui/src/svelte/AppShellSidebar.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { appShellSidebarVariants } from '../shared/appShellVariants'
import { useAppShellContext } from './appShellContext'

type Props = HTMLAttributes<HTMLElement> & {
  label?: string
  class?: string
  children?: Snippet
}

let { label = 'Sidebar', class: className, children, ...rest }: Props = $props()

const ctx = useAppShellContext('AppShellSidebar')
const classes = $derived(appShellSidebarVariants({ class: className }))

let el: HTMLElement
$effect(() => {
  if (el) ctx.setSidebar(el)
})
</script>

<aside
  bind:this={el}
  id={ctx.sidebarId}
  class={classes}
  aria-label={label}
  popover="auto"
  {...rest}
>
  {@render children?.()}
</aside>
