// packages/zui/src/vue/AppShell.vue
<template>
  <div :id="rootId" ref="rootRef" :class="classes" v-bind="$attrs">
    <a class="zui-app-shell-skip-link" :href="`#${mainId}`">Skip to main content</a>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import {
  AppShellController,
  type AppShellMode,
} from '../shared/AppShellController'
import { appShellVariants } from '../shared/appShellVariants'
import { provideAppShellContext } from './appShellContext'

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    id?: string
    class?: string
    position?: 'left' | 'right'
    defaultCollapsed?: boolean
    collapsed?: boolean
    mobileBreakpoint?: number
    storageKey?: string | null
    shortcut?: boolean
  }>(),
  {
    defaultCollapsed: false,
    mobileBreakpoint: 768,
    shortcut: false,
  },
)

const emit = defineEmits<{
  (e: 'collapsedChange', collapsed: boolean): void
}>()

const uid = Math.random().toString(36).slice(2, 9)
const rootId = props.id ?? `zui-app-shell-${uid}`
const sidebarId = `${rootId}-sidebar`
const mainId = `${rootId}-main`

const rootRef = ref<HTMLDivElement | null>(null)
const sidebarRef = ref<HTMLElement | null>(null)
let controller: AppShellController | undefined
const mode = ref<AppShellMode>('desktop')

provideAppShellContext({
  rootId,
  sidebarId,
  mainId,
  setSidebar: (el) => {
    sidebarRef.value = el
  },
  getController: () => controller,
  toggle: () => controller?.toggle(),
  getMode: () => mode.value,
})

onMounted(() => {
  if (!rootRef.value || !sidebarRef.value) return
  controller = new AppShellController({
    root: rootRef.value,
    sidebar: sidebarRef.value,
    defaultCollapsed: props.defaultCollapsed,
    collapsed: props.collapsed,
    mobileBreakpoint: props.mobileBreakpoint,
    storageKey: props.storageKey === undefined ? undefined : props.storageKey,
    bindKeyboardShortcut: props.shortcut,
    onCollapsedChange: (v) => emit('collapsedChange', v),
  })
  controller.mount()
  controller.onModeChange((m) => (mode.value = m))
})

onBeforeUnmount(() => {
  controller?.destroy()
  controller = undefined
})

watch(
  () => props.collapsed,
  (next) => {
    if (next !== undefined) controller?.syncCollapsed(next)
  },
)

const classes = computed(() =>
  appShellVariants({ class: props.class, position: props.position }),
)
</script>

// packages/zui/src/svelte/AppShell.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { onMount } from 'svelte'
import {
  AppShellController,
  type AppShellMode,
} from '../shared/AppShellController'
import { appShellVariants } from '../shared/appShellVariants'
import { provideAppShellContext } from './appShellContext'

type Props = HTMLAttributes<HTMLDivElement> & {
  position?: 'left' | 'right'
  defaultCollapsed?: boolean
  collapsed?: boolean
  onCollapsedChange?: (collapsed: boolean) => void
  mobileBreakpoint?: number
  storageKey?: string | null
  shortcut?: boolean
  class?: string
  children?: Snippet
}

let {
  position,
  defaultCollapsed = false,
  collapsed,
  onCollapsedChange,
  mobileBreakpoint = 768,
  storageKey,
  shortcut = false,
  class: className,
  id,
  children,
  ...rest
}: Props = $props()

const uid = Math.random().toString(36).slice(2, 9)
const rootId = id ?? `zui-app-shell-${uid}`
const sidebarId = `${rootId}-sidebar`
const mainId = `${rootId}-main`

let rootEl: HTMLDivElement
let sidebarEl: HTMLElement | undefined
let controller: AppShellController | undefined
let mode = $state<AppShellMode>('desktop')

provideAppShellContext({
  rootId,
  sidebarId,
  mainId,
  setSidebar: (el) => {
    sidebarEl = el
  },
  getController: () => controller,
  toggle: () => controller?.toggle(),
  mode: () => mode,
})

onMount(() => {
  if (!sidebarEl) return
  controller = new AppShellController({
    root: rootEl,
    sidebar: sidebarEl,
    defaultCollapsed,
    collapsed,
    mobileBreakpoint,
    storageKey: storageKey === undefined ? undefined : storageKey,
    bindKeyboardShortcut: shortcut,
    onCollapsedChange,
  })
  controller.mount()
  const off = controller.onModeChange((m) => (mode = m))
  return () => {
    off()
    controller?.destroy()
  }
})

$effect(() => {
  if (collapsed !== undefined && controller) {
    controller.syncCollapsed(collapsed)
  }
})

const classes = $derived(appShellVariants({ class: className, position }))
</script>

<div bind:this={rootEl} {id} class={classes} {...rest}>
  <a class="zui-app-shell-skip-link" href={`#${mainId}`}>Skip to main content</a>
  {@render children?.()}
</div>
