// packages/zui/src/react/Badge.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { badgeVariants } from '../shared/badgeVariants'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

export type BadgeProps = HTMLAttributes<HTMLSpanElement> &
  BadgeVariantProps & {
    className?: string
  }

export function Badge({
  className,
  variant,
  color,
  shape,
  size,
  children,
  ...props
}: BadgeProps) {
  const classes = badgeVariants({ className, color, shape, size, variant })
  return (
    <span className={classes} {...props}>
      {children}
    </span>
  )
}

// packages/zui/src/svelte/Badge.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { badgeVariants } from '../shared/badgeVariants'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

type Props = HTMLAttributes<HTMLSpanElement> & {
  class?: string
  variant?: BadgeVariantProps['variant']
  color?: BadgeVariantProps['color']
  shape?: BadgeVariantProps['shape']
  size?: BadgeVariantProps['size']
  children?: Snippet
}

let {
  class: className,
  variant,
  color,
  shape,
  size,
  children,
  ...rest
}: Props = $props()

const classes = $derived(badgeVariants({ className, color, shape, size, variant }))
</script>

<span class={classes} {...rest}>
  {@render children?.()}
</span>
