// src/react/Dialog.tsx
import { forwardRef, useEffect, useRef, type DialogHTMLAttributes } from 'react'
import type { VariantProps } from 'cva'
import { dialogVariants } from '../shared/dialogVariants'

type DialogVariantProps = VariantProps<typeof dialogVariants>

export type DialogProps = DialogHTMLAttributes<HTMLDialogElement> &
  DialogVariantProps & {
    open?: boolean
    onClose?: () => void
    /** Controls how the dialog can be dismissed. Defaults to `"any"` (backdrop click or Esc). */
    closedby?: 'any' | 'closerequest' | 'none'
  }

export const Dialog = forwardRef<HTMLDialogElement, DialogProps>(
  function Dialog({ open, onClose, className, size, position, closedby = 'any', children, ...props }, forwardedRef) {
    const innerRef = useRef<HTMLDialogElement>(null)
    const ref = (forwardedRef ?? innerRef) as React.RefObject<HTMLDialogElement>
    const classes = dialogVariants({ size, position, className })

    useEffect(() => {
      if (open) {
        ref.current?.showModal()
      } else {
        ref.current?.close()
      }
    }, [open])

    useEffect(() => {
      ref.current?.setAttribute('closedby', closedby)
    }, [closedby])

    return (
      <dialog ref={ref} className={classes} onClose={onClose} {...props}>
        {children}
      </dialog>
    )
  },
)

// packages/zui/src/svelte/Dialog.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLDialogAttributes } from 'svelte/elements'
import { dialogVariants } from '../shared/dialogVariants'

type DialogVariantProps = VariantProps<typeof dialogVariants>

type Props = HTMLDialogAttributes & {
  class?: string
  open?: boolean
  size?: DialogVariantProps['size']
  position?: DialogVariantProps['position']
  /** Controls how the dialog can be dismissed. Defaults to `"any"`. */
  closedby?: 'any' | 'closerequest' | 'none'
  onclose?: (event: Event) => void
  children?: Snippet
}

let {
  class: className,
  open = false,
  size,
  position,
  closedby = 'any',
  onclose,
  children,
  ...rest
}: Props = $props()

let dialogRef = $state<HTMLDialogElement | null>(null)
const classes = $derived(dialogVariants({ className, position, size }))

$effect(() => {
  if (!dialogRef) return
  if (open) {
    if (!dialogRef.open) dialogRef.showModal()
  } else if (dialogRef.open) {
    dialogRef.close()
  }
})

$effect(() => {
  if (!dialogRef) return
  dialogRef.setAttribute('closedby', closedby ?? 'any')
})
</script>

<dialog
  bind:this={dialogRef}
  class={classes}
  onclose={onclose}
  {...rest}
>
  {@render children?.()}
</dialog>
