// packages/zui/src/react/DialogHeader.tsx
import type { HTMLAttributes } from 'react'

export type DialogHeaderProps = HTMLAttributes<HTMLDivElement>

export function DialogHeader({
  className,
  children,
  ...props
}: DialogHeaderProps) {
  return (
    <div
      className={['zui-dialog-header', className].filter(Boolean).join(' ')}
      {...props}
    >
      {children}
    </div>
  )
}

// packages/zui/src/svelte/DialogHeader.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-dialog-header', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>
