// packages/zui/src/react/FieldGroup.tsx
import type { HTMLAttributes } from 'react'

export type FieldGroupProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldGroup({ className, children, ...props }: FieldGroupProps) {
  const classes = ['zui-field-group', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/svelte/FieldGroup.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-field-group', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>
