// packages/zui/src/react/FieldSeparator.tsx
import type { HTMLAttributes } from 'react'

export type FieldSeparatorProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldSeparator({
  className,
  children,
  ...props
}: FieldSeparatorProps) {
  const classes = ['zui-field-separator', className].filter(Boolean).join(' ')
  return (
    <div className={classes} role="separator" {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/svelte/FieldSeparator.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-field-separator', className].filter(Boolean).join(' '),
)
</script>

<div role="separator" class={classes} {...rest}>
  {@render children?.()}
</div>
