// packages/zui/src/react/FieldSet.tsx
import type { HTMLAttributes } from 'react'

export type FieldSetProps = HTMLAttributes<HTMLFieldSetElement> & {
  className?: string
}

export function FieldSet({ className, children, ...props }: FieldSetProps) {
  const classes = ['zui-field-set', className].filter(Boolean).join(' ')
  return (
    <fieldset className={classes} {...props}>
      {children}
    </fieldset>
  )
}

// packages/zui/src/svelte/FieldSet.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLFieldSetElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(['zui-field-set', className].filter(Boolean).join(' '))
</script>

<fieldset class={classes} {...rest}>
  {@render children?.()}
</fieldset>
