// packages/zui/src/react/Kbd.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { kbdVariants } from '../shared/kbdVariants'

type KbdVariantProps = VariantProps<typeof kbdVariants>

export type KbdProps = HTMLAttributes<HTMLElement> &
  KbdVariantProps & {
    className?: string
  }

export function Kbd({ className, shape, children, ...props }: KbdProps) {
  const classes = kbdVariants({ className, shape })
  return (
    <kbd className={classes} {...props}>
      {children}
    </kbd>
  )
}

// packages/zui/src/svelte/Kbd.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { kbdVariants } from '../shared/kbdVariants'

type KbdVariantProps = VariantProps<typeof kbdVariants>

type Props = HTMLAttributes<HTMLElement> & {
  class?: string
  shape?: KbdVariantProps['shape']
  children?: Snippet
}

let { class: className, shape, children, ...rest }: Props = $props()

const classes = $derived(kbdVariants({ className, shape }))
</script>

<kbd class={classes} {...rest}>
  {@render children?.()}
</kbd>
