// packages/zui/src/react/KbdGroup.tsx
import type { HTMLAttributes } from 'react'

export type KbdGroupProps = HTMLAttributes<HTMLElement> & {
  className?: string
}

export function KbdGroup({ className, children, ...props }: KbdGroupProps) {
  const classes = ['zui-kbd-group', className].filter(Boolean).join(' ')
  return (
    <kbd className={classes} {...props}>
      {children}
    </kbd>
  )
}

// packages/zui/src/svelte/KbdGroup.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(['zui-kbd-group', className].filter(Boolean).join(' '))
</script>

<kbd class={classes} {...rest}>
  {@render children?.()}
</kbd>
