// packages/zui/src/solid/MenuContent.tsx
import type { JSX } from 'solid-js'
import { createEffect, onCleanup, splitProps } from 'solid-js'
import { useMenuContext } from './menuContext'

export type MenuContentProps = JSX.HTMLAttributes<HTMLDivElement>

export function MenuContent(props: MenuContentProps) {
  const [local, rest] = splitProps(props, ['class', 'onKeyDown'])
  const { controller, snapshot } = useMenuContext()
  const contentId = controller.getSnapshot().contentId
  let ref: HTMLDivElement | undefined

  createEffect(() => {
    const unregister = controller.registerContent({
      contentId,
      element: ref ?? null,
    })
    onCleanup(unregister)
  })

  return (
    <div
      {...rest}
      ref={ref}
      aria-labelledby={snapshot().triggerId}
      class={['zui-menu-content', local.class].filter(Boolean).join(' ')}
      data-align={snapshot().align}
      data-side={snapshot().side}
      data-state={snapshot().open ? 'open' : 'closed'}
      data-zui-menu-content=""
      popover="manual"
      id={snapshot().contentId}
      onKeyDown={(event) => {
        local.onKeyDown?.(event)
        if (!event.defaultPrevented) controller.handleContentKeydown(event)
      }}
      role="menu"
    />
  )
}

// packages/zui/src/svelte/MenuContent.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { getMenuContext } from './menuContext'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, onkeydown, ...rest }: Props = $props()
const { controller, getSnapshot } = getMenuContext()
const contentId = controller.getSnapshot().contentId
let ref = $state<HTMLDivElement | undefined>()

$effect(() => controller.registerContent({ contentId, element: ref ?? null }))
</script>

<div
  {...rest}
  bind:this={ref}
  aria-labelledby={getSnapshot().triggerId}
  class={['zui-menu-content', className].filter(Boolean).join(' ')}
  data-align={getSnapshot().align}
  data-side={getSnapshot().side}
  data-state={getSnapshot().open ? 'open' : 'closed'}
  data-zui-menu-content=""
  popover="manual"
  id={getSnapshot().contentId}
  on:keydown={(event) => {
    onkeydown?.(event)
    if (!event.defaultPrevented) controller.handleContentKeydown(event)
  }}
  role="menu"
>
  {@render children?.()}
</div>
