// packages/zui/src/solid/Popover.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { popoverVariants } from '../shared/popoverVariants'

type PopoverVariantProps = VariantProps<typeof popoverVariants>

export type PopoverProps = JSX.HTMLAttributes<HTMLDivElement> &
  PopoverVariantProps & {
    id: string
    popover?: 'auto' | 'manual'
  }

export function Popover(props: PopoverProps) {
  const [local, rest] = splitProps(props, [
    'id',
    'popover',
    'class',
    'shape',
    'style',
    'children',
  ])
  const classes = () =>
    popoverVariants({ class: local.class, shape: local.shape })
  const anchorStyle = (): JSX.CSSProperties => ({
    'position-anchor': `--${local.id}`,
    ...(typeof local.style === 'object' ? local.style : {}),
  })

  return (
    <div
      id={local.id}
      popover={local.popover ?? 'auto'}
      class={classes()}
      style={anchorStyle()}
      {...rest}
    >
      {local.children}
    </div>
  )
}

// packages/zui/src/svelte/Popover.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { popoverVariants } from '../shared/popoverVariants'

type PopoverVariantProps = VariantProps<typeof popoverVariants>

type Props = HTMLAttributes<HTMLDivElement> & {
  id: string
  popover?: 'auto' | 'manual'
  class?: string
  shape?: PopoverVariantProps['shape']
  children?: Snippet
}

let {
  id,
  popover = 'auto',
  class: className,
  shape,
  children,
  ...rest
}: Props = $props()

const classes = $derived(popoverVariants({ className, shape }))
const mergedStyle = $derived(
  rest.style
    ? `position-anchor: --${id}; ${rest.style}`
    : `position-anchor: --${id};`,
)
</script>

<div {id} {popover} class={classes} {...rest} style={mergedStyle}>
  {@render children?.()}
</div>
