// src/react/TableBody.tsx
import type { HTMLAttributes } from 'react'

export type TableBodyProps = HTMLAttributes<HTMLTableSectionElement> & {
  className?: string
}

export function TableBody({ className, children, ...props }: TableBodyProps) {
  const classes = ['zui-table-body', className].filter(Boolean).join(' ')
  return (
    <tbody className={classes} {...props}>
      {children}
    </tbody>
  )
}

// packages/zui/src/svelte/TableBody.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLTableSectionElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-table-body', className].filter(Boolean).join(' '),
)
</script>

<tbody class={classes} {...rest}>
  {@render children?.()}
</tbody>
