// src/react/TableCaption.tsx
import type { HTMLAttributes } from 'react'

export type TableCaptionProps = HTMLAttributes<HTMLTableCaptionElement> & {
  className?: string
}

export function TableCaption({
  className,
  children,
  ...props
}: TableCaptionProps) {
  const classes = ['zui-table-caption', className].filter(Boolean).join(' ')
  return (
    <caption className={classes} {...props}>
      {children}
    </caption>
  )
}

// packages/zui/src/svelte/TableCaption.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLTableCaptionElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-table-caption', className].filter(Boolean).join(' '),
)
</script>

<caption class={classes} {...rest}>
  {@render children?.()}
</caption>
