// packages/zui/src/vue/Tabs.vue
<template>
  <div
    v-bind="$attrs"
    ref="rootRef"
    :class="classes"
    :data-disabled="snapshot.disabled ? 'true' : undefined"
    :data-orientation="snapshot.orientation"
    data-zui-tabs-root=""
    :id="snapshot.rootId"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed, onUnmounted, ref, watchEffect } from 'vue'
import {
  createTabsController,
  type TabsActivationMode,
  type TabsDirection,
  type TabsOrientation,
} from '../core/tabs'
import { tabsVariants } from '../shared/tabsVariants'
import { provideTabsContext } from './tabsContext'

defineOptions({ inheritAttrs: false })

type TabsVariantProps = VariantProps<typeof tabsVariants>

const props = defineProps<{
  activationMode?: TabsActivationMode
  class?: string
  defaultValue?: string
  dir?: TabsDirection
  disabled?: boolean
  id?: string
  onValueChange?: (value: string) => void
  orientation?: TabsOrientation
  shape?: TabsVariantProps['shape']
  value?: string
}>()

const controller = createTabsController({
  activationMode: props.activationMode,
  defaultValue: props.defaultValue,
  dir: props.dir,
  disabled: props.disabled,
  id: props.id,
  onValueChange: props.onValueChange,
  orientation: props.orientation,
  value: props.value,
})

const rootRef = ref<HTMLDivElement>()
const snapshot = ref(controller.getSnapshot())
const unsubscribe = controller.subscribe((next) => {
  snapshot.value = next
})

watchEffect(() => {
  controller.setOptions({
    activationMode: props.activationMode,
    defaultValue: props.defaultValue,
    dir: props.dir,
    disabled: props.disabled,
    id: props.id,
    onValueChange: props.onValueChange,
    orientation: props.orientation,
    value: props.value,
  })
})

onUnmounted(unsubscribe)

provideTabsContext({
  controller,
  rootRef,
  snapshot,
})

const classes = computed(() =>
  tabsVariants({ className: props.class, shape: props.shape }),
)
</script>

// packages/zui/src/svelte/Tabs.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import {
  createTabsController,
  type TabsActivationMode,
  type TabsDirection,
  type TabsOrientation,
} from '../core/tabs'
import { tabsVariants } from '../shared/tabsVariants'
import { setTabsContext } from './tabsContext'

type TabsVariantProps = VariantProps<typeof tabsVariants>

type Props = HTMLAttributes<HTMLDivElement> & {
  activationMode?: TabsActivationMode
  defaultValue?: string
  dir?: TabsDirection
  disabled?: boolean
  id?: string
  onValueChange?: (value: string) => void
  orientation?: TabsOrientation
  value?: string
  shape?: TabsVariantProps['shape']
  class?: string
  children?: Snippet
}

let {
  activationMode,
  class: className,
  defaultValue,
  dir,
  disabled,
  id,
  onValueChange,
  orientation,
  shape,
  value,
  children,
  ...rest
}: Props = $props()

let root = $state<HTMLDivElement | undefined>()
const controller = createTabsController({
  activationMode,
  defaultValue,
  dir,
  disabled,
  id,
  onValueChange,
  orientation,
  value,
})
let snapshot = $state(controller.getSnapshot())

const unsubscribe = controller.subscribe((next) => {
  snapshot = next
})

$effect(() => {
  controller.setOptions({
    activationMode,
    defaultValue,
    dir,
    disabled,
    id,
    onValueChange,
    orientation,
    value,
  })
})

$effect(() => unsubscribe)

setTabsContext({
  controller,
  getRoot: () => root,
  getSnapshot: () => snapshot,
})

const classes = $derived(tabsVariants({ className, shape }))
</script>

<div
  {...rest}
  bind:this={root}
  class={classes}
  data-disabled={snapshot.disabled ? 'true' : undefined}
  data-orientation={snapshot.orientation}
  data-zui-tabs-root=""
  id={snapshot.rootId}
>
  {@render children?.()}
</div>
