// src/react/Button.tsx
import type { VariantProps } from 'cva'
import type { AnchorHTMLAttributes, ButtonHTMLAttributes } from 'react'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

type ButtonBaseProps = ButtonVariantProps & {
  className?: string
}

type ButtonAsButton = ButtonBaseProps &
  ButtonHTMLAttributes<HTMLButtonElement> & {
    href?: never
  }

type ButtonAsAnchor = ButtonBaseProps &
  AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
  }

export type ButtonProps = ButtonAsButton | ButtonAsAnchor

export function Button({
  className,
  variant,
  color,
  size,
  shape,
  icon,
  ...props
}: ButtonProps) {
  const classes = buttonVariants({
    className,
    color,
    icon,
    shape,
    size,
    variant,
  })

  if ('href' in props && props.href) {
    return (
      <a
        className={classes}
        {...(props as AnchorHTMLAttributes<HTMLAnchorElement>)}
      />
    )
  }

  return (
    <button
      className={classes}
      {...(props as ButtonHTMLAttributes<HTMLButtonElement>)}
    />
  )
}

// src/vue/Button.vue
<template>
  <a v-if="href" :class="classes" :href="href" v-bind="$attrs">
    <slot />
  </a>
  <button v-else :class="classes" v-bind="$attrs">
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { VariantProps } from 'cva'
import { buttonVariants } from '../shared/buttonVariants'

defineOptions({ inheritAttrs: false })

type ButtonVariantProps = VariantProps<typeof buttonVariants>

const props = withDefaults(defineProps<{
  class?: string
  href?: string
  variant?: ButtonVariantProps['variant']
  color?: ButtonVariantProps['color']
  size?: ButtonVariantProps['size']
  shape?: ButtonVariantProps['shape']
  icon?: ButtonVariantProps['icon']
}>(), {})

const classes = computed(() => buttonVariants({ variant: props.variant, color: props.color, size: props.size, shape: props.shape, icon: props.icon, className: props.class }))
</script>
