// src/svelte/MenuItem.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type {
    HTMLAnchorAttributes,
    HTMLButtonAttributes,
  } from 'svelte/elements'
  import type { VariantProps } from 'cva'
  import { buttonVariants } from '../shared/buttonVariants'

  type ButtonVariantProps = VariantProps<typeof buttonVariants>

  type Props = (HTMLButtonAttributes & HTMLAnchorAttributes) & {
    class?: string
    href?: string
    variant?: ButtonVariantProps['variant']
    color?: ButtonVariantProps['color']
    size?: ButtonVariantProps['size']
    shape?: ButtonVariantProps['shape']
    icon?: ButtonVariantProps['icon']
    children?: Snippet
  }

  let {
    class: className,
    href,
    variant = 'ghost',
    color,
    size,
    shape,
    icon,
    children,
    ...rest
  }: Props = $props()

  const classes = $derived(
    buttonVariants({
      variant,
      color,
      size,
      shape,
      icon,
      className: ['zui-menu-item', className].filter(Boolean).join(' '),
    }),
  )
</script>

{#if href}
  <a class={classes} {href} {...rest}>
    {@render children?.()}
  </a>
{:else}
  <button class={classes} {...rest}>
    {@render children?.()}
  </button>
{/if}

// src/vue/MenuItem.vue
<template>
  <a v-if="href" :class="classes" :href="href" v-bind="$attrs">
    <slot />
  </a>
  <button v-else :class="classes" v-bind="$attrs">
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { VariantProps } from 'cva'
import { buttonVariants } from '../shared/buttonVariants'

defineOptions({ inheritAttrs: false })

type ButtonVariantProps = VariantProps<typeof buttonVariants>

const props = withDefaults(defineProps<{
  class?: string
  href?: string
  variant?: ButtonVariantProps['variant']
  color?: ButtonVariantProps['color']
  size?: ButtonVariantProps['size']
  shape?: ButtonVariantProps['shape']
  icon?: ButtonVariantProps['icon']
}>(), {
  variant: 'ghost',
})

const classes = computed(() => buttonVariants({ variant: props.variant, color: props.color, size: props.size, shape: props.shape, icon: props.icon, className: ['zui-menu-item', props.class].filter(Boolean).join(' ') }))
</script>
