// packages/zui/src/solid/AccordionTrigger.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type AccordionTriggerProps = JSX.HTMLAttributes<HTMLElement>

export function AccordionTrigger(props: AccordionTriggerProps) {
  const [local, rest] = splitProps(props, ['class'])
  const classes = () =>
    ['zui-accordion-trigger', local.class].filter(Boolean).join(' ')
  return <summary class={classes()} {...rest} />
}

// src/react/AccordionTrigger.tsx
import type { HTMLAttributes } from 'react'

export type AccordionTriggerProps = HTMLAttributes<HTMLElement>

export function AccordionTrigger({ className, ...props }: AccordionTriggerProps) {
  const classes = ['zui-accordion-trigger', className].filter(Boolean).join(' ')
  return <summary className={classes} {...props} />
}
