// packages/zui/src/solid/Badge.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { badgeVariants } from '../shared/badgeVariants'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

export type BadgeProps = JSX.HTMLAttributes<HTMLSpanElement> &
  BadgeVariantProps & {
    class?: string
  }

export function Badge(props: BadgeProps) {
  const [local, rest] = splitProps(props, [
    'class',
    'variant',
    'color',
    'children',
  ])
  const classes = () =>
    badgeVariants({
      className: local.class,
      color: local.color,
      variant: local.variant,
    })
  return (
    <span class={classes()} {...rest}>
      {local.children}
    </span>
  )
}

// src/react/Badge.tsx
import type { HTMLAttributes } from 'react'
import type { VariantProps } from 'cva'
import { badgeVariants } from '../shared/badgeVariants'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

export type BadgeProps = HTMLAttributes<HTMLSpanElement> &
  BadgeVariantProps & {
    className?: string
  }

export function Badge({ className, variant, color, children, ...props }: BadgeProps) {
  const classes = badgeVariants({ variant, color, className })
  return <span className={classes} {...props}>{children}</span>
}
