// src/vue/CardHeader.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-card-header', props.class].filter(Boolean).join(' '),
)
</script>

// src/react/CardHeader.tsx
import type { HTMLAttributes } from 'react'

export type CardHeaderProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardHeader({ className, children, ...props }: CardHeaderProps) {
  const classes = ['zui-card-header', className].filter(Boolean).join(' ')
  return <div className={classes} {...props}>{children}</div>
}
