// src/svelte/CollapsibleContent.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-collapsible-content', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// src/react/CollapsibleContent.tsx
import type { HTMLAttributes } from 'react'

export type CollapsibleContentProps = HTMLAttributes<HTMLDivElement>

export function CollapsibleContent({
  className,
  ...props
}: CollapsibleContentProps) {
  const classes = ['zui-collapsible-content', className]
    .filter(Boolean)
    .join(' ')
  return <div className={classes} {...props} />
}
