// src/solid/Collapsible.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type CollapsibleProps = JSX.DetailsHtmlAttributes<HTMLDetailsElement> & {
  open?: boolean
}

export function Collapsible(props: CollapsibleProps) {
  const [local, rest] = splitProps(props, ['class'])
  const classes = () =>
    ['zui-collapsible', local.class].filter(Boolean).join(' ')
  return <details class={classes()} {...rest} />
}

// src/react/Collapsible.tsx
import type { HTMLAttributes } from 'react'

export type CollapsibleProps = HTMLAttributes<HTMLDetailsElement> & {
  open?: boolean
}

export function Collapsible({ className, ...props }: CollapsibleProps) {
  const classes = ['zui-collapsible', className].filter(Boolean).join(' ')
  return <details className={classes} {...props} />
}
