// src/svelte/Collapsible.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDetailsElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-collapsible', className].filter(Boolean).join(' '),
  )
</script>

<details class={classes} {...rest}>
  {@render children?.()}
</details>

// src/react/Collapsible.tsx
import type { HTMLAttributes } from 'react'

export type CollapsibleProps = HTMLAttributes<HTMLDetailsElement> & {
  open?: boolean
}

export function Collapsible({ className, ...props }: CollapsibleProps) {
  const classes = ['zui-collapsible', className].filter(Boolean).join(' ')
  return <details className={classes} {...props} />
}
