// src/svelte/CollapsibleTrigger.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-collapsible-trigger', className].filter(Boolean).join(' '),
  )
</script>

<summary class={classes} {...rest}>
  {@render children?.()}
</summary>

// src/react/CollapsibleTrigger.tsx
import type { HTMLAttributes } from 'react'

export type CollapsibleTriggerProps = HTMLAttributes<HTMLElement>

export function CollapsibleTrigger({
  className,
  ...props
}: CollapsibleTriggerProps) {
  const classes = ['zui-collapsible-trigger', className]
    .filter(Boolean)
    .join(' ')
  return <summary className={classes} {...props} />
}
