// src/svelte/DialogFooter.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-dialog-footer', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// src/react/DialogFooter.tsx
import type { HTMLAttributes } from 'react'

export type DialogFooterProps = HTMLAttributes<HTMLDivElement>

export function DialogFooter({ className, children, ...props }: DialogFooterProps) {
  return (
    <div className={['zui-dialog-footer', className].filter(Boolean).join(' ')} {...props}>
      {children}
    </div>
  )
}
