// packages/zui/src/solid/DialogTitle.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type DialogTitleProps = JSX.HTMLAttributes<HTMLHeadingElement>

export function DialogTitle(props: DialogTitleProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-dialog-title', local.class].filter(Boolean).join(' ')
  return (
    <h2 class={classes()} {...rest}>
      {local.children}
    </h2>
  )
}

// src/react/DialogTitle.tsx
import type { HTMLAttributes } from 'react'

export type DialogTitleProps = HTMLAttributes<HTMLHeadingElement>

export function DialogTitle({
  className,
  children,
  ...props
}: DialogTitleProps) {
  return (
    <h2
      className={['zui-dialog-title', className].filter(Boolean).join(' ')}
      {...props}
    >
      {children}
    </h2>
  )
}
