// src/solid/Dialog.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { createEffect, splitProps } from 'solid-js'
import { dialogVariants } from '../shared/dialogVariants'

type DialogVariantProps = VariantProps<typeof dialogVariants>

export type DialogProps = JSX.DialogHtmlAttributes<HTMLDialogElement> &
  DialogVariantProps & {
    open?: boolean
    onClose?: () => void
    closedby?: 'any' | 'closerequest' | 'none'
  }

export function Dialog(props: DialogProps) {
  let ref: HTMLDialogElement | undefined
  const [local, rest] = splitProps(props, [
    'open',
    'onClose',
    'class',
    'size',
    'position',
    'closedby',
    'children',
  ])
  const classes = () =>
    dialogVariants({
      className: local.class,
      position: local.position,
      size: local.size,
    })

  createEffect(() => {
    if (local.open) {
      ref?.showModal()
    } else {
      ref?.close()
    }
  })

  createEffect(() => {
    ref?.setAttribute('closedby', local.closedby ?? 'any')
  })

  return (
    <dialog ref={ref} class={classes()} onClose={local.onClose} {...rest}>
      {local.children}
    </dialog>
  )
}

// src/react/Dialog.tsx
import { forwardRef, useEffect, useRef, type DialogHTMLAttributes } from 'react'
import type { VariantProps } from 'cva'
import { dialogVariants } from '../shared/dialogVariants'

type DialogVariantProps = VariantProps<typeof dialogVariants>

export type DialogProps = DialogHTMLAttributes<HTMLDialogElement> &
  DialogVariantProps & {
    open?: boolean
    onClose?: () => void
    /** Controls how the dialog can be dismissed. Defaults to `"any"` (backdrop click or Esc). */
    closedby?: 'any' | 'closerequest' | 'none'
  }

export const Dialog = forwardRef<HTMLDialogElement, DialogProps>(
  function Dialog({ open, onClose, className, size, position, closedby = 'any', children, ...props }, forwardedRef) {
    const innerRef = useRef<HTMLDialogElement>(null)
    const ref = (forwardedRef ?? innerRef) as React.RefObject<HTMLDialogElement>
    const classes = dialogVariants({ size, position, className })

    useEffect(() => {
      if (open) {
        ref.current?.showModal()
      } else {
        ref.current?.close()
      }
    }, [open])

    useEffect(() => {
      ref.current?.setAttribute('closedby', closedby)
    }, [closedby])

    return (
      <dialog ref={ref} className={classes} onClose={onClose} {...props}>
        {children}
      </dialog>
    )
  },
)
