// src/vue/Input.vue
<template>
  <input :class="classes" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() => ['zui-input', props.class].filter(Boolean).join(' '))
</script>

// src/react/Input.tsx
import type { InputHTMLAttributes } from 'react'

export type InputProps = InputHTMLAttributes<HTMLInputElement> & {
  className?: string
}

export function Input({ className, ...props }: InputProps) {
  const classes = ['zui-input', className].filter(Boolean).join(' ')
  return <input className={classes} {...props} />
}
