// src/svelte/Menu.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDetailsElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(['zui-menu', className].filter(Boolean).join(' '))
</script>

<details class={classes} {...rest}>
  {@render children?.()}
</details>

// src/react/Menu.tsx
import type { HTMLAttributes } from 'react'

export type MenuProps = HTMLAttributes<HTMLDetailsElement> & {
  open?: boolean
}

export function Menu({ className, ...props }: MenuProps) {
  const classes = ['zui-menu', className].filter(Boolean).join(' ')
  return <details className={classes} {...props} />
}
