// src/solid/MenuItem.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import type { VariantProps } from 'cva'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type MenuItemProps = ButtonVariantProps &
	JSX.ButtonHTMLAttributes<HTMLButtonElement> &
	JSX.AnchorHTMLAttributes<HTMLAnchorElement> & {
		class?: string
		href?: string
	}

export function MenuItem(props: MenuItemProps) {
	const [local, rest] = splitProps(props, [
		'class',
		'variant',
		'color',
		'size',
		'shape',
		'icon',
		'href',
	])
	const classes = () =>
		buttonVariants({
			variant: local.variant ?? 'ghost',
			color: local.color,
			size: local.size,
			shape: local.shape,
			icon: local.icon,
			className: ['zui-menu-item', local.class].filter(Boolean).join(' '),
		})

	return (
		<>
			{local.href ? (
				<a
					class={classes()}
					href={local.href}
					{...(rest as JSX.AnchorHTMLAttributes<HTMLAnchorElement>)}
				/>
			) : (
				<button
					class={classes()}
					{...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
				/>
			)}
		</>
	)
}

// src/react/MenuItem.tsx
import type { ButtonHTMLAttributes, AnchorHTMLAttributes } from 'react'
import type { VariantProps } from 'cva'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

type MenuItemBase = ButtonVariantProps & { className?: string }

type MenuItemAsButton = MenuItemBase &
  ButtonHTMLAttributes<HTMLButtonElement> & {
    href?: never
  }

type MenuItemAsAnchor = MenuItemBase &
  AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
  }

export type MenuItemProps = MenuItemAsButton | MenuItemAsAnchor

export function MenuItem({ className, variant = 'ghost', color, size, shape, icon, ...props }: MenuItemProps) {
  const classes = buttonVariants({ variant, color, size, shape, icon, className: ['zui-menu-item', className].filter(Boolean).join(' ') })

  if ('href' in props && props.href) {
    return <a className={classes} {...(props as AnchorHTMLAttributes<HTMLAnchorElement>)} />
  }

  return <button className={classes} {...(props as ButtonHTMLAttributes<HTMLButtonElement>)} />
}
