// packages/zui/src/solid/Pre.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type PreProps = JSX.HTMLAttributes<HTMLPreElement> & {
  class?: string
}

export function Pre(props: PreProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-pre', local.class].filter(Boolean).join(' ')
  return (
    <pre class={classes()} {...rest}>
      {local.children}
    </pre>
  )
}

// src/react/Pre.tsx
import type { HTMLAttributes } from 'react'

export type PreProps = HTMLAttributes<HTMLPreElement> & {
  className?: string
}

export function Pre({ className, children, ...props }: PreProps) {
  const classes = ['zui-pre', className].filter(Boolean).join(' ')
  return <pre className={classes} {...props}>{children}</pre>
}
