// src/solid/Prose.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type ProseProps = JSX.HTMLAttributes<HTMLDivElement> & {
  class?: string
}

export function Prose(props: ProseProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['prose', local.class].filter(Boolean).join(' ')
  return (
    <div class={classes()} {...rest}>
      {local.children}
    </div>
  )
}

// src/react/Prose.tsx
import type { HTMLAttributes } from 'react'

export type ProseProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function Prose({ className, children, ...props }: ProseProps) {
  const classes = ['prose', className].filter(Boolean).join(' ')
  return <div className={classes} {...props}>{children}</div>
}
