// src/solid/Select.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type SelectProps = JSX.SelectHTMLAttributes<HTMLSelectElement> & {
	class?: string
}

export function Select(props: SelectProps) {
	const [local, rest] = splitProps(props, ['class', 'children'])
	const classes = () => ['zui-select', local.class].filter(Boolean).join(' ')
	return (
		<select class={classes()} {...rest}>
			{local.children}
		</select>
	)
}

// src/react/Select.tsx
import type { SelectHTMLAttributes } from 'react'

export type SelectProps = SelectHTMLAttributes<HTMLSelectElement> & {
  className?: string
}

export function Select({ className, children, ...props }: SelectProps) {
  const classes = ['zui-select', className].filter(Boolean).join(' ')
  return <select className={classes} {...props}>{children}</select>
}
