// src/solid/TableHead.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TableHeadProps = JSX.ThHTMLAttributes<HTMLTableCellElement> & {
  class?: string
}

export function TableHead(props: TableHeadProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-table-head', local.class].filter(Boolean).join(' ')
  return (
    <th class={classes()} {...rest}>
      {local.children}
    </th>
  )
}

// src/react/TableHead.tsx
import type { ThHTMLAttributes } from 'react'

export type TableHeadProps = ThHTMLAttributes<HTMLTableCellElement> & {
  className?: string
}

export function TableHead({ className, children, ...props }: TableHeadProps) {
  const classes = ['zui-table-head', className].filter(Boolean).join(' ')
  return <th className={classes} {...props}>{children}</th>
}
