// src/vue/TableHead.vue
<template>
  <th :class="classes" v-bind="$attrs">
    <slot />
  </th>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-table-head', props.class].filter(Boolean).join(' '),
)
</script>

// src/react/TableHead.tsx
import type { ThHTMLAttributes } from 'react'

export type TableHeadProps = ThHTMLAttributes<HTMLTableCellElement> & {
  className?: string
}

export function TableHead({ className, children, ...props }: TableHeadProps) {
  const classes = ['zui-table-head', className].filter(Boolean).join(' ')
  return <th className={classes} {...props}>{children}</th>
}
