// src/svelte/TableHead.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLThAttributes } from 'svelte/elements'

type Props = HTMLThAttributes & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-table-head', className].filter(Boolean).join(' '),
)
</script>

<th class={classes} {...rest}>
  {@render children?.()}
</th>

// src/react/TableHead.tsx
import type { ThHTMLAttributes } from 'react'

export type TableHeadProps = ThHTMLAttributes<HTMLTableCellElement> & {
  className?: string
}

export function TableHead({ className, children, ...props }: TableHeadProps) {
  const classes = ['zui-table-head', className].filter(Boolean).join(' ')
  return <th className={classes} {...props}>{children}</th>
}
