// packages/zui/src/svelte/Text.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { type TextSize, textSizeClass } from '../shared/textSizeClass'

type Props = HTMLAttributes<HTMLSpanElement> & {
  class?: string
  size?: TextSize
  children?: Snippet
}

let { class: className, size = '0', children, ...rest }: Props = $props()

const classes = $derived(
  [textSizeClass(size), className].filter(Boolean).join(' '),
)
</script>

<span class={classes} {...rest}>
  {@render children?.()}
</span>

// src/react/Text.tsx
import type { HTMLAttributes } from 'react'
import { textSizeClass, type TextSize } from '../shared/textSizeClass'

export type TextProps = HTMLAttributes<HTMLSpanElement> & {
  size?: TextSize
  className?: string
}

export function Text({ size = '0', className, children, ...props }: TextProps) {
  const classes = [textSizeClass(size), className].filter(Boolean).join(' ')
  return <span className={classes} {...props}>{children}</span>
}
