// src/solid/Text.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { textSizeClass, type TextSize } from '../shared/textSizeClass'

export type TextProps = JSX.HTMLAttributes<HTMLSpanElement> & {
	size?: TextSize
	class?: string
}

export function Text(props: TextProps) {
	const [local, rest] = splitProps(props, ['size', 'class', 'children'])
	const classes = () =>
		[textSizeClass(local.size ?? '0'), local.class].filter(Boolean).join(' ')
	return (
		<span class={classes()} {...rest}>
			{local.children}
		</span>
	)
}

// src/react/Text.tsx
import type { HTMLAttributes } from 'react'
import { textSizeClass, type TextSize } from '../shared/textSizeClass'

export type TextProps = HTMLAttributes<HTMLSpanElement> & {
  size?: TextSize
  className?: string
}

export function Text({ size = '0', className, children, ...props }: TextProps) {
  const classes = [textSizeClass(size), className].filter(Boolean).join(' ')
  return <span className={classes} {...props}>{children}</span>
}
