// src/svelte/AccordionTrigger.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-accordion-trigger', className].filter(Boolean).join(' '),
  )
</script>

<summary class={classes} {...rest}>
  {@render children?.()}
</summary>

// packages/zui/src/react/AccordionTrigger.tsx
import type { HTMLAttributes } from 'react'

export type AccordionTriggerProps = HTMLAttributes<HTMLElement>

export function AccordionTrigger({
  className,
  ...props
}: AccordionTriggerProps) {
  const classes = ['zui-accordion-trigger', className].filter(Boolean).join(' ')
  return <summary className={classes} {...props} />
}
