// src/svelte/AccordionItem.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDetailsElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-accordion-item', className].filter(Boolean).join(' '),
  )
</script>

<details class={classes} {...rest}>
  {@render children?.()}
</details>

// packages/zui/src/react/AccordionItem.tsx
import type { HTMLAttributes } from 'react'

export type AccordionItemProps = HTMLAttributes<HTMLDetailsElement> & {
  open?: boolean
  name?: string
}

export function AccordionItem({ className, ...props }: AccordionItemProps) {
  const classes = ['zui-accordion-item', className].filter(Boolean).join(' ')
  return <details className={classes} {...props} />
}
