// src/svelte/AccordionContent.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-accordion-content', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/zui/src/react/AccordionContent.tsx
import type { HTMLAttributes } from 'react'

export type AccordionContentProps = HTMLAttributes<HTMLDivElement>

export function AccordionContent({
  className,
  ...props
}: AccordionContentProps) {
  const classes = ['zui-accordion-content', className].filter(Boolean).join(' ')
  return <div className={classes} {...props} />
}
