// packages/zui/src/solid/Badge.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { badgeVariants } from '../shared/badgeVariants'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

export type BadgeProps = JSX.HTMLAttributes<HTMLSpanElement> &
  BadgeVariantProps & {
    class?: string
  }

export function Badge(props: BadgeProps) {
  const [local, rest] = splitProps(props, [
    'class',
    'variant',
    'color',
    'shape',
    'size',
    'children',
  ])
  const classes = () =>
    badgeVariants({
      className: local.class,
      color: local.color,
      shape: local.shape,
      size: local.size,
      variant: local.variant,
    })
  return (
    <span class={classes()} {...rest}>
      {local.children}
    </span>
  )
}

// packages/zui/src/react/Badge.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { badgeVariants } from '../shared/badgeVariants'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

export type BadgeProps = HTMLAttributes<HTMLSpanElement> &
  BadgeVariantProps & {
    className?: string
  }

export function Badge({
  className,
  variant,
  color,
  shape,
  size,
  children,
  ...props
}: BadgeProps) {
  const classes = badgeVariants({ className, color, shape, size, variant })
  return (
    <span className={classes} {...props}>
      {children}
    </span>
  )
}
