// packages/zui/src/solid/Card.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { cardVariants } from '../shared/cardVariants'

type CardVariantProps = VariantProps<typeof cardVariants>

export type CardProps = JSX.HTMLAttributes<HTMLDivElement> &
  JSX.AnchorHTMLAttributes<HTMLAnchorElement> &
  CardVariantProps & {
    class?: string
    href?: string
  }

export function Card(props: CardProps) {
  const [local, rest] = splitProps(props, [
    'class',
    'href',
    'shape',
    'children',
  ])
  const classes = () =>
    cardVariants({
      class: [local.href && 'zui-card-interactive', local.class]
        .filter(Boolean)
        .join(' '),
      shape: local.shape,
    })

  return (
    <>
      {local.href ? (
        <a
          class={classes()}
          href={local.href}
          {...(rest as JSX.AnchorHTMLAttributes<HTMLAnchorElement>)}
        >
          {local.children}
        </a>
      ) : (
        <div
          class={classes()}
          {...(rest as JSX.HTMLAttributes<HTMLDivElement>)}
        >
          {local.children}
        </div>
      )}
    </>
  )
}

// packages/zui/src/react/Card.tsx
import type { VariantProps } from 'cva'
import type { AnchorHTMLAttributes, HTMLAttributes } from 'react'
import { cardVariants } from '../shared/cardVariants'

type CardBaseProps = VariantProps<typeof cardVariants> & {
  className?: string
}

type CardAsDiv = CardBaseProps &
  HTMLAttributes<HTMLDivElement> & {
    href?: never
  }

type CardAsAnchor = CardBaseProps &
  AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
  }

export type CardProps = CardAsDiv | CardAsAnchor

export function Card({ className, shape, ...props }: CardProps) {
  const classes = cardVariants({
    className: [
      'href' in props && props.href && 'zui-card-interactive',
      className,
    ]
      .filter(Boolean)
      .join(' '),
    shape,
  })

  if ('href' in props && props.href) {
    return (
      <a
        className={classes}
        {...(props as AnchorHTMLAttributes<HTMLAnchorElement>)}
      />
    )
  }

  return (
    <div className={classes} {...(props as HTMLAttributes<HTMLDivElement>)} />
  )
}
