// src/vue/CardBody.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-card-body', props.class].filter(Boolean).join(' '),
)
</script>

// packages/zui/src/react/CardBody.tsx
import type { HTMLAttributes } from 'react'

export type CardBodyProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardBody({ className, children, ...props }: CardBodyProps) {
  const classes = ['zui-card-body', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
