// src/svelte/CardTitle.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDivElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-card-title', className].filter(Boolean).join(' '),
  )
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/zui/src/react/CardTitle.tsx
import type { HTMLAttributes } from 'react'

export type CardTitleProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardTitle({ className, children, ...props }: CardTitleProps) {
  const classes = ['zui-card-title', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
