// src/svelte/CardBody.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(['zui-card-body', className].filter(Boolean).join(' '))
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/zui/src/react/CardBody.tsx
import type { HTMLAttributes } from 'react'

export type CardBodyProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function CardBody({ className, children, ...props }: CardBodyProps) {
  const classes = ['zui-card-body', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
