// src/solid/Card.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type CardProps = JSX.HTMLAttributes<HTMLDivElement> &
	JSX.AnchorHTMLAttributes<HTMLAnchorElement> & {
		class?: string
		href?: string
	}

export function Card(props: CardProps) {
	const [local, rest] = splitProps(props, ['class', 'href'])
	const classes = () =>
		['zui-card', local.href && 'zui-card-interactive', local.class]
			.filter(Boolean)
			.join(' ')

	return (
		<>
			{local.href ? (
				<a
					class={classes()}
					href={local.href}
					{...(rest as JSX.AnchorHTMLAttributes<HTMLAnchorElement>)}
				/>
			) : (
				<div
					class={classes()}
					{...(rest as JSX.HTMLAttributes<HTMLDivElement>)}
				/>
			)}
		</>
	)
}

// packages/zui/src/react/Card.tsx
import type { AnchorHTMLAttributes, HTMLAttributes } from 'react'

type CardBaseProps = {
  className?: string
}

type CardAsDiv = CardBaseProps &
  HTMLAttributes<HTMLDivElement> & {
    href?: never
  }

type CardAsAnchor = CardBaseProps &
  AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
  }

export type CardProps = CardAsDiv | CardAsAnchor

export function Card({ className, ...props }: CardProps) {
  const classes = [
    'zui-card',
    'href' in props && props.href && 'zui-card-interactive',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  if ('href' in props && props.href) {
    return (
      <a
        className={classes}
        {...(props as AnchorHTMLAttributes<HTMLAnchorElement>)}
      />
    )
  }

  return (
    <div className={classes} {...(props as HTMLAttributes<HTMLDivElement>)} />
  )
}
