// src/vue/Checkbox.vue
<template>
  <label :class="classes" v-bind="$attrs">
    <input type="checkbox" />
    <slot />
  </label>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() => ['zui-checkbox', props.class].filter(Boolean).join(' '))
</script>

// packages/zui/src/react/Checkbox.tsx
import type { InputHTMLAttributes } from 'react'

export type CheckboxProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type'
> & {
  className?: string
}

export function Checkbox({ className, children, ...props }: CheckboxProps) {
  const classes = ['zui-checkbox', className].filter(Boolean).join(' ')
  return (
    <label className={classes}>
      <input type="checkbox" {...props} />
      {children}
    </label>
  )
}
