// src/svelte/Checkbox.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLInputAttributes } from 'svelte/elements'

  type Props = Omit<HTMLInputAttributes, 'type'> & {
    class?: string
    checked?: boolean
    children?: Snippet
  }

  let {
    class: className,
    checked = $bindable(false),
    children,
    ...rest
  }: Props = $props()

  const classes = $derived(
    ['zui-checkbox', className].filter(Boolean).join(' '),
  )
</script>

<label class={classes}>
  <input type="checkbox" bind:checked {...rest} />
  {@render children?.()}
</label>

// packages/zui/src/react/Checkbox.tsx
import type { InputHTMLAttributes } from 'react'

export type CheckboxProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type'
> & {
  className?: string
}

export function Checkbox({ className, children, ...props }: CheckboxProps) {
  const classes = ['zui-checkbox', className].filter(Boolean).join(' ')
  return (
    <label className={classes}>
      <input type="checkbox" {...props} />
      {children}
    </label>
  )
}
