// src/solid/DialogBody.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type DialogBodyProps = JSX.HTMLAttributes<HTMLDivElement>

export function DialogBody(props: DialogBodyProps) {
	const [local, rest] = splitProps(props, ['class', 'children'])
	const classes = () =>
		['zui-dialog-body', local.class].filter(Boolean).join(' ')
	return (
		<div class={classes()} {...rest}>
			{local.children}
		</div>
	)
}

// packages/zui/src/react/DialogBody.tsx
import type { HTMLAttributes } from 'react'

export type DialogBodyProps = HTMLAttributes<HTMLDivElement>

export function DialogBody({ className, children, ...props }: DialogBodyProps) {
  return (
    <div
      className={['zui-dialog-body', className].filter(Boolean).join(' ')}
      {...props}
    >
      {children}
    </div>
  )
}
