// src/svelte/DialogBody.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-dialog-body', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/zui/src/react/DialogBody.tsx
import type { HTMLAttributes } from 'react'

export type DialogBodyProps = HTMLAttributes<HTMLDivElement>

export function DialogBody({ className, children, ...props }: DialogBodyProps) {
  return (
    <div
      className={['zui-dialog-body', className].filter(Boolean).join(' ')}
      {...props}
    >
      {children}
    </div>
  )
}
