// packages/zui/src/svelte/DialogDescription.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLParagraphElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-dialog-description', className].filter(Boolean).join(' '),
)
</script>

<p class={classes} {...rest}>
  {@render children?.()}
</p>

// packages/zui/src/react/DialogDescription.tsx
import type { HTMLAttributes } from 'react'

export type DialogDescriptionProps = HTMLAttributes<HTMLParagraphElement>

export function DialogDescription({
  className,
  children,
  ...props
}: DialogDescriptionProps) {
  return (
    <p
      className={['zui-dialog-description', className]
        .filter(Boolean)
        .join(' ')}
      {...props}
    >
      {children}
    </p>
  )
}
