// packages/zui/src/svelte/FieldDescription.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-field-description', className].filter(Boolean).join(' '),
)
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/zui/src/react/FieldDescription.tsx
import type { HTMLAttributes } from 'react'

export type FieldDescriptionProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldDescription({
  className,
  children,
  ...props
}: FieldDescriptionProps) {
  const classes = ['zui-field-description', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
