// packages/zui/src/vue/FieldLegend.vue
<template>
  <legend :class="classes" v-bind="$attrs">
    <slot />
  </legend>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { fieldLegendVariants } from '../shared/fieldLegendVariants'

defineOptions({ inheritAttrs: false })

type FieldLegendVariantProps = VariantProps<typeof fieldLegendVariants>

const props = defineProps<{
  class?: string
  variant?: FieldLegendVariantProps['variant']
}>()

const classes = computed(() =>
  fieldLegendVariants({
    variant: props.variant,
    className: props.class,
  }),
)
</script>

// packages/zui/src/react/FieldLegend.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { fieldLegendVariants } from '../shared/fieldLegendVariants'

type FieldLegendVariantProps = VariantProps<typeof fieldLegendVariants>

export type FieldLegendProps = HTMLAttributes<HTMLLegendElement> &
  FieldLegendVariantProps & {
    className?: string
  }

export function FieldLegend({
  className,
  variant,
  children,
  ...props
}: FieldLegendProps) {
  const classes = fieldLegendVariants({
    className,
    variant,
  })
  return (
    <legend className={classes} {...props}>
      {children}
    </legend>
  )
}
