// packages/zui/src/svelte/FieldError.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLDivElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(
  ['zui-field-error', className].filter(Boolean).join(' '),
)
</script>

<div role="alert" class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/zui/src/react/FieldError.tsx
import type { HTMLAttributes } from 'react'

export type FieldErrorProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldError({ className, children, ...props }: FieldErrorProps) {
  const classes = ['zui-field-error', className].filter(Boolean).join(' ')
  return (
    <div className={classes} role="alert" {...props}>
      {children}
    </div>
  )
}
