// packages/zui/src/vue/FieldSet.vue
<template>
  <fieldset :class="classes" v-bind="$attrs">
    <slot />
  </fieldset>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-field-set', props.class].filter(Boolean).join(' '),
)
</script>

// packages/zui/src/react/FieldSet.tsx
import type { HTMLAttributes } from 'react'

export type FieldSetProps = HTMLAttributes<HTMLFieldSetElement> & {
  className?: string
}

export function FieldSet({ className, children, ...props }: FieldSetProps) {
  const classes = ['zui-field-set', className].filter(Boolean).join(' ')
  return (
    <fieldset className={classes} {...props}>
      {children}
    </fieldset>
  )
}
