// packages/zui/src/solid/FieldError.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type FieldErrorProps = JSX.HTMLAttributes<HTMLDivElement> & {
  class?: string
}

export function FieldError(props: FieldErrorProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-field-error', local.class].filter(Boolean).join(' ')
  return (
    <div role="alert" class={classes()} {...rest}>
      {local.children}
    </div>
  )
}

// packages/zui/src/react/FieldError.tsx
import type { HTMLAttributes } from 'react'

export type FieldErrorProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldError({ className, children, ...props }: FieldErrorProps) {
  const classes = ['zui-field-error', className].filter(Boolean).join(' ')
  return (
    <div className={classes} role="alert" {...props}>
      {children}
    </div>
  )
}
