// packages/zui/src/vue/FieldDescription.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-field-description', props.class].filter(Boolean).join(' '),
)
</script>

// packages/zui/src/react/FieldDescription.tsx
import type { HTMLAttributes } from 'react'

export type FieldDescriptionProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldDescription({
  className,
  children,
  ...props
}: FieldDescriptionProps) {
  const classes = ['zui-field-description', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
