// packages/zui/src/vue/FieldGroup.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-field-group', props.class].filter(Boolean).join(' '),
)
</script>

// packages/zui/src/react/FieldGroup.tsx
import type { HTMLAttributes } from 'react'

export type FieldGroupProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldGroup({ className, children, ...props }: FieldGroupProps) {
  const classes = ['zui-field-group', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
