// packages/zui/src/vue/Flex.vue
<template>
  <div :class="classes" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { flexVariants } from '../shared/flexVariants'

defineOptions({ inheritAttrs: false })

type FlexVariantProps = VariantProps<typeof flexVariants>

const props = withDefaults(
  defineProps<{
    class?: string
    display?: FlexVariantProps['display']
    direction?: FlexVariantProps['direction']
    align?: FlexVariantProps['align']
    justify?: FlexVariantProps['justify']
    wrap?: FlexVariantProps['wrap']
    gap?: FlexVariantProps['gap']
    gapX?: FlexVariantProps['gapX']
    gapY?: FlexVariantProps['gapY']
  }>(),
  {},
)

const classes = computed(() =>
  flexVariants({
    align: props.align,
    className: props.class,
    direction: props.direction,
    display: props.display,
    gap: props.gap,
    gapX: props.gapX,
    gapY: props.gapY,
    justify: props.justify,
    wrap: props.wrap,
  }),
)
</script>

// packages/zui/src/react/Flex.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { flexVariants } from '../shared/flexVariants'

type FlexVariantProps = VariantProps<typeof flexVariants>

export type FlexProps = HTMLAttributes<HTMLDivElement> &
  FlexVariantProps & {
    className?: string
  }

export function Flex({
  className,
  display,
  direction,
  align,
  justify,
  wrap,
  gap,
  gapX,
  gapY,
  children,
  ...props
}: FlexProps) {
  const classes = flexVariants({
    align,
    className,
    direction,
    display,
    gap,
    gapX,
    gapY,
    justify,
    wrap,
  })
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}
