// packages/zui/src/vue/Kbd.vue
<template>
  <kbd :class="classes" v-bind="$attrs">
    <slot />
  </kbd>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { kbdVariants } from '../shared/kbdVariants'

defineOptions({ inheritAttrs: false })

type KbdVariantProps = VariantProps<typeof kbdVariants>

const props = defineProps<{
  class?: string
  shape?: KbdVariantProps['shape']
}>()

const classes = computed(() =>
  kbdVariants({ className: props.class, shape: props.shape }),
)
</script>

// packages/zui/src/react/Kbd.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { kbdVariants } from '../shared/kbdVariants'

type KbdVariantProps = VariantProps<typeof kbdVariants>

export type KbdProps = HTMLAttributes<HTMLElement> &
  KbdVariantProps & {
    className?: string
  }

export function Kbd({ className, shape, children, ...props }: KbdProps) {
  const classes = kbdVariants({ className, shape })
  return (
    <kbd className={classes} {...props}>
      {children}
    </kbd>
  )
}
