// packages/zui/src/solid/KbdGroup.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type KbdGroupProps = JSX.HTMLAttributes<HTMLElement> & {
  class?: string
}

export function KbdGroup(props: KbdGroupProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-kbd-group', local.class].filter(Boolean).join(' ')
  return (
    <kbd class={classes()} {...rest}>
      {local.children}
    </kbd>
  )
}

// packages/zui/src/react/KbdGroup.tsx
import type { HTMLAttributes } from 'react'

export type KbdGroupProps = HTMLAttributes<HTMLElement> & {
  className?: string
}

export function KbdGroup({ className, children, ...props }: KbdGroupProps) {
  const classes = ['zui-kbd-group', className].filter(Boolean).join(' ')
  return (
    <kbd className={classes} {...props}>
      {children}
    </kbd>
  )
}
