// packages/zui/src/vue/KbdGroup.vue
<template>
  <kbd :class="classes" v-bind="$attrs">
    <slot />
  </kbd>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['zui-kbd-group', props.class].filter(Boolean).join(' '),
)
</script>

// packages/zui/src/react/KbdGroup.tsx
import type { HTMLAttributes } from 'react'

export type KbdGroupProps = HTMLAttributes<HTMLElement> & {
  className?: string
}

export function KbdGroup({ className, children, ...props }: KbdGroupProps) {
  const classes = ['zui-kbd-group', className].filter(Boolean).join(' ')
  return (
    <kbd className={classes} {...props}>
      {children}
    </kbd>
  )
}
