// packages/zui/src/svelte/Label.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLLabelAttributes } from 'svelte/elements'

type Props = HTMLLabelAttributes & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(['zui-label', className].filter(Boolean).join(' '))
</script>

<label class={classes} {...rest}>
  {@render children?.()}
</label>

// packages/zui/src/react/Label.tsx
import type { LabelHTMLAttributes } from 'react'

export type LabelProps = LabelHTMLAttributes<HTMLLabelElement> & {
  className?: string
}

export function Label({ className, children, ...props }: LabelProps) {
  const classes = ['zui-label', className].filter(Boolean).join(' ')
  return (
    <label className={classes} {...props}>
      {children}
    </label>
  )
}
