// packages/zui/src/solid/MenuItem.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { createEffect, createUniqueId, onCleanup, splitProps } from 'solid-js'
import { createMenuItemId } from '../core/menu'
import { buttonVariants } from '../shared/buttonVariants'
import { getMenuItemOrder, useMenuContext } from './menuContext'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type MenuItemProps = ButtonVariantProps &
  JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  JSX.AnchorHTMLAttributes<HTMLAnchorElement> & {
    class?: string
    disabled?: boolean
    href?: string
    id?: string
    textValue?: string
  }

export function MenuItem(props: MenuItemProps) {
  const generatedId = createUniqueId()
  const [local, rest] = splitProps(props, [
    'class',
    'color',
    'disabled',
    'href',
    'icon',
    'id',
    'onClick',
    'onFocus',
    'onPointerEnter',
    'shape',
    'size',
    'textValue',
    'variant',
  ])
  const { controller, rootRef, snapshot } = useMenuContext()
  const fallbackId = createMenuItemId(snapshot().rootId, `solid-${generatedId}`)
  const itemId = () => local.id ?? fallbackId
  let ref: HTMLElement | undefined

  createEffect(() => {
    const unregister = controller.registerItem({
      disabled: local.disabled ?? false,
      element: ref ?? null,
      id: itemId(),
      kind: local.href ? 'link' : 'button',
      order: getMenuItemOrder(rootRef(), ref),
      textValue: local.textValue,
    })
    onCleanup(unregister)
  })

  const highlighted = () => snapshot().highlightedItemId === itemId()
  const classes = () =>
    buttonVariants({
      className: ['zui-menu-item', local.class].filter(Boolean).join(' '),
      color: local.color,
      icon: local.icon,
      shape: local.shape,
      size: local.size,
      variant: local.variant ?? 'ghost',
    })

  return local.href ? (
    <a
      {...(rest as JSX.AnchorHTMLAttributes<HTMLAnchorElement>)}
      ref={ref as HTMLAnchorElement}
      aria-disabled={snapshot().disabled || local.disabled ? 'true' : undefined}
      class={classes()}
      data-disabled={snapshot().disabled || local.disabled ? 'true' : undefined}
      data-highlighted={highlighted() ? 'true' : undefined}
      data-text-value={local.textValue}
      data-zui-menu-item=""
      href={local.href}
      id={itemId()}
      onClick={(event) => {
        local.onClick?.(event)
        if (!event.defaultPrevented) {
          const accepted = controller.selectItem(itemId())
          if (!accepted && (snapshot().disabled || local.disabled))
            event.preventDefault()
        }
      }}
      onFocus={(event) => {
        local.onFocus?.(event)
        if (!event.defaultPrevented) controller.focusItem(itemId())
      }}
      onPointerEnter={(event) => {
        local.onPointerEnter?.(event)
        if (!event.defaultPrevented) controller.handleItemPointerEnter(itemId())
      }}
      role="menuitem"
      tabIndex={snapshot().open && highlighted() ? 0 : -1}
    />
  ) : (
    <button
      {...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
      ref={ref as HTMLButtonElement}
      class={classes()}
      data-disabled={snapshot().disabled || local.disabled ? 'true' : undefined}
      data-highlighted={highlighted() ? 'true' : undefined}
      data-text-value={local.textValue}
      data-zui-menu-item=""
      disabled={snapshot().disabled || local.disabled}
      id={itemId()}
      onClick={(event) => {
        local.onClick?.(event)
        if (!event.defaultPrevented) controller.selectItem(itemId())
      }}
      onFocus={(event) => {
        local.onFocus?.(event)
        if (!event.defaultPrevented) controller.focusItem(itemId())
      }}
      onPointerEnter={(event) => {
        local.onPointerEnter?.(event)
        if (!event.defaultPrevented) controller.handleItemPointerEnter(itemId())
      }}
      role="menuitem"
      tabIndex={snapshot().open && highlighted() ? 0 : -1}
      type="button"
    />
  )
}

// packages/zui/src/react/MenuItem.tsx
import type { VariantProps } from 'cva'
import type {
  AnchorHTMLAttributes,
  ButtonHTMLAttributes,
  FocusEvent,
  MouseEvent,
  PointerEvent,
} from 'react'
import { useEffect, useId, useRef } from 'react'
import { createMenuItemId } from '../core/menu'
import { buttonVariants } from '../shared/buttonVariants'
import { getMenuItemOrder, useMenuContext, useMenuSnapshot } from './menuContext'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

type MenuItemBase = ButtonVariantProps & {
  className?: string
  disabled?: boolean
  id?: string
  textValue?: string
}

type MenuItemAsButton = MenuItemBase &
  ButtonHTMLAttributes<HTMLButtonElement> & {
    href?: never
  }

type MenuItemAsAnchor = MenuItemBase &
  AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
  }

export type MenuItemProps = MenuItemAsButton | MenuItemAsAnchor

export function MenuItem({
  className,
  disabled = false,
  variant = 'ghost',
  color,
  size,
  shape,
  icon,
  id,
  textValue,
  ...props
}: MenuItemProps) {
  const generatedId = useId()
  const { controller, rootRef } = useMenuContext()
  const snapshot = useMenuSnapshot()
  const itemId =
    id ??
    createMenuItemId(snapshot.rootId, `react-${generatedId.replace(/:/g, '')}`)
  const ref = useRef<HTMLElement>(null)
  const highlighted = snapshot.highlightedItemId === itemId
  const isLink = 'href' in props && Boolean(props.href)
  const classes = buttonVariants({
    className: ['zui-menu-item', className].filter(Boolean).join(' '),
    color,
    icon,
    shape,
    size,
    variant,
  })

  useEffect(() => {
    return controller.registerItem({
      disabled,
      element: ref.current,
      id: itemId,
      kind: isLink ? 'link' : 'button',
      order: getMenuItemOrder(rootRef.current, ref.current),
      textValue,
    })
  }, [controller, disabled, isLink, itemId, rootRef, textValue])

  const handleClick = (event: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => {
    ;(
      props as {
        onClick?: (event: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void
      }
    ).onClick?.(event)

    if (!event.defaultPrevented) {
      const accepted = controller.selectItem(itemId)
      if (!accepted && (snapshot.disabled || disabled)) {
        event.preventDefault()
      }
    }
  }

  const handleFocus = (event: FocusEvent<HTMLButtonElement | HTMLAnchorElement>) => {
    ;(
      props as {
        onFocus?: (event: FocusEvent<HTMLButtonElement | HTMLAnchorElement>) => void
      }
    ).onFocus?.(event)

    if (!event.defaultPrevented) controller.focusItem(itemId)
  }

  const handlePointerEnter = (
    event: PointerEvent<HTMLButtonElement | HTMLAnchorElement>,
  ) => {
    ;(
      props as {
        onPointerEnter?: (
          event: PointerEvent<HTMLButtonElement | HTMLAnchorElement>,
        ) => void
      }
    ).onPointerEnter?.(event)

    if (!event.defaultPrevented) controller.handleItemPointerEnter(itemId)
  }

  const commonProps = {
    className: classes,
    'data-disabled': snapshot.disabled || disabled ? 'true' : undefined,
    'data-highlighted': highlighted ? 'true' : undefined,
    'data-text-value': textValue,
    'data-zui-menu-item': '',
    id: itemId,
    onClick: handleClick,
    onFocus: handleFocus,
    onPointerEnter: handlePointerEnter,
    ref,
    role: 'menuitem' as const,
    tabIndex: snapshot.open && highlighted ? 0 : -1,
  }

  if (isLink) {
    const { href, ...anchorProps } = props as AnchorHTMLAttributes<HTMLAnchorElement>
    return (
      <a
        {...anchorProps}
        {...commonProps}
        aria-disabled={snapshot.disabled || disabled ? 'true' : undefined}
        href={href}
      />
    )
  }

  const buttonProps = props as ButtonHTMLAttributes<HTMLButtonElement>
  return (
    <button
      {...buttonProps}
      {...commonProps}
      disabled={snapshot.disabled || disabled}
      type={buttonProps.type ?? 'button'}
    />
  )
}
