// src/solid/MenuTrigger.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import type { VariantProps } from 'cva'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type MenuTriggerProps = JSX.HTMLAttributes<HTMLElement> & ButtonVariantProps

export function MenuTrigger(props: MenuTriggerProps) {
	const [local, rest] = splitProps(props, [
		'class',
		'variant',
		'color',
		'size',
		'shape',
		'icon',
	])
	const classes = () =>
		buttonVariants({
			variant: local.variant ?? 'outline',
			color: local.color,
			size: local.size,
			shape: local.shape,
			icon: local.icon,
			className: local.class,
		})
	return <summary class={classes()} {...rest} />
}

// packages/zui/src/react/MenuTrigger.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { buttonVariants } from '../shared/buttonVariants'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type MenuTriggerProps = HTMLAttributes<HTMLElement> & ButtonVariantProps

export function MenuTrigger({
  className,
  variant = 'outline',
  color,
  size,
  shape,
  icon,
  ...props
}: MenuTriggerProps) {
  const classes = buttonVariants({
    className,
    color,
    icon,
    shape,
    size,
    variant,
  })
  return <summary className={classes} {...props} />
}
