// src/svelte/Pre.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLPreElement> & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(['zui-pre', className].filter(Boolean).join(' '))
</script>

<pre class={classes} {...rest}>{@render children?.()}</pre>

// packages/zui/src/react/Pre.tsx
import type { HTMLAttributes } from 'react'

export type PreProps = HTMLAttributes<HTMLPreElement> & {
  className?: string
}

export function Pre({ className, children, ...props }: PreProps) {
  const classes = ['zui-pre', className].filter(Boolean).join(' ')
  return (
    <pre className={classes} {...props}>
      {children}
    </pre>
  )
}
