// packages/zui/src/vue/Select.vue
<template>
  <select :class="classes" v-bind="$attrs">
    <slot />
  </select>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { selectVariants } from '../shared/selectVariants'

defineOptions({ inheritAttrs: false })

type SelectVariantProps = VariantProps<typeof selectVariants>

const props = defineProps<{
  class?: string
  shape?: SelectVariantProps['shape']
}>()

const classes = computed(() =>
  selectVariants({ className: props.class, shape: props.shape }),
)
</script>

// packages/zui/src/react/Select.tsx
import type { VariantProps } from 'cva'
import type { SelectHTMLAttributes } from 'react'
import { selectVariants } from '../shared/selectVariants'

type SelectVariantProps = VariantProps<typeof selectVariants>

export type SelectProps = SelectHTMLAttributes<HTMLSelectElement> &
  SelectVariantProps & {
    className?: string
  }

export function Select({ className, shape, children, ...props }: SelectProps) {
  const classes = selectVariants({ className, shape })
  return (
    <select className={classes} {...props}>
      {children}
    </select>
  )
}
