// src/svelte/TableCell.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLTdAttributes } from 'svelte/elements'

  type Props = HTMLTdAttributes & {
    class?: string
    children?: Snippet
  }

  let { class: className, children, ...rest }: Props = $props()

  const classes = $derived(
    ['zui-table-cell', className].filter(Boolean).join(' '),
  )
</script>

<td class={classes} {...rest}>
  {@render children?.()}
</td>

// packages/zui/src/react/TableCell.tsx
import type { TdHTMLAttributes } from 'react'

export type TableCellProps = TdHTMLAttributes<HTMLTableCellElement> & {
  className?: string
}

export function TableCell({ className, children, ...props }: TableCellProps) {
  const classes = ['zui-table-cell', className].filter(Boolean).join(' ')
  return (
    <td className={classes} {...props}>
      {children}
    </td>
  )
}
