// src/svelte/Table.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLTableAttributes } from 'svelte/elements'

type Props = HTMLTableAttributes & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(['zui-table', className].filter(Boolean).join(' '))
</script>

<table class={classes} {...rest}>
  {@render children?.()}
</table>

// packages/zui/src/react/Table.tsx
import type { TableHTMLAttributes } from 'react'

export type TableProps = TableHTMLAttributes<HTMLTableElement> & {
  className?: string
}

export function Table({ className, children, ...props }: TableProps) {
  const classes = ['zui-table', className].filter(Boolean).join(' ')
  return (
    <table className={classes} {...props}>
      {children}
    </table>
  )
}
