// src/svelte/TableRow.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'

type Props = HTMLAttributes<HTMLTableRowElement> & {
  class?: string
  children?: Snippet
}

let { class: className, children, ...rest }: Props = $props()

const classes = $derived(['zui-table-row', className].filter(Boolean).join(' '))
</script>

<tr class={classes} {...rest}>
  {@render children?.()}
</tr>

// packages/zui/src/react/TableRow.tsx
import type { HTMLAttributes } from 'react'

export type TableRowProps = HTMLAttributes<HTMLTableRowElement> & {
  className?: string
}

export function TableRow({ className, children, ...props }: TableRowProps) {
  const classes = ['zui-table-row', className].filter(Boolean).join(' ')
  return (
    <tr className={classes} {...props}>
      {children}
    </tr>
  )
}
