// packages/zui/src/svelte/TabsList.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLAttributes } from 'svelte/elements'
import { tabsListVariants } from '../shared/tabsVariants'
import { getTabsContext } from './tabsContext'

type TabsListVariantProps = VariantProps<typeof tabsListVariants>

type Props = HTMLAttributes<HTMLDivElement> & TabsListVariantProps & {
  class?: string
  children?: Snippet
}

let { class: className, children, variant, ...rest }: Props = $props()
const { getSnapshot } = getTabsContext()
const classes = $derived(tabsListVariants({ className, variant }))
const snapshot = $derived(getSnapshot())
</script>

<div
  {...rest}
  class={classes}
  data-orientation={snapshot.orientation}
  data-zui-tabs-list=""
  role="tablist"
  aria-orientation={snapshot.orientation === 'vertical' ? 'vertical' : undefined}
>
  {@render children?.()}
</div>

// packages/zui/src/react/TabsList.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { tabsListVariants } from '../shared/tabsVariants'
import { useTabsSnapshot } from './tabsContext'

type TabsListVariantProps = VariantProps<typeof tabsListVariants>

export type TabsListProps = HTMLAttributes<HTMLDivElement> & TabsListVariantProps

export function TabsList({ children, className, variant, ...props }: TabsListProps) {
  const snapshot = useTabsSnapshot()
  const classes = tabsListVariants({ className, variant })

  return (
    <div
      {...props}
      className={classes}
      data-orientation={snapshot.orientation}
      data-zui-tabs-list=""
      role="tablist"
      aria-orientation={
        snapshot.orientation === 'vertical' ? 'vertical' : undefined
      }
    >
      {children}
    </div>
  )
}
