// packages/zui/src/vue/TabsList.vue
<template>
  <div
    v-bind="$attrs"
    :class="classes"
    :data-orientation="snapshot.orientation"
    data-zui-tabs-list=""
    role="tablist"
    :aria-orientation="snapshot.orientation === 'vertical' ? 'vertical' : undefined"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { tabsListVariants } from '../shared/tabsVariants'
import { useTabsContext } from './tabsContext'

defineOptions({ inheritAttrs: false })

type TabsListVariantProps = VariantProps<typeof tabsListVariants>

const props = defineProps<{
  class?: string
  variant?: TabsListVariantProps['variant']
}>()

const { snapshot } = useTabsContext()
const classes = computed(() =>
  tabsListVariants({ className: props.class, variant: props.variant }),
)
</script>

// packages/zui/src/react/TabsList.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { tabsListVariants } from '../shared/tabsVariants'
import { useTabsSnapshot } from './tabsContext'

type TabsListVariantProps = VariantProps<typeof tabsListVariants>

export type TabsListProps = HTMLAttributes<HTMLDivElement> & TabsListVariantProps

export function TabsList({ children, className, variant, ...props }: TabsListProps) {
  const snapshot = useTabsSnapshot()
  const classes = tabsListVariants({ className, variant })

  return (
    <div
      {...props}
      className={classes}
      data-orientation={snapshot.orientation}
      data-zui-tabs-list=""
      role="tablist"
      aria-orientation={
        snapshot.orientation === 'vertical' ? 'vertical' : undefined
      }
    >
      {children}
    </div>
  )
}
