// packages/zui/src/solid/tabsContext.tsx
import type { Accessor } from 'solid-js'
import { createContext, useContext } from 'solid-js'
import type { TabsControllerApi, TabsSnapshot } from '../core/tabs'

export interface TabsContextValue {
  controller: TabsControllerApi
  rootRef: Accessor<HTMLDivElement | undefined>
  snapshot: Accessor<TabsSnapshot>
}

export const TabsContext = createContext<TabsContextValue>()

export function useTabsContext() {
  const context = useContext(TabsContext)

  if (!context) {
    throw new Error('Tabs components must be used within <Tabs>.')
  }

  return context
}

export function getTabsTriggerOrder(
  root: HTMLDivElement | undefined,
  element: HTMLElement | undefined,
) {
  if (!root || !element) return 0

  return [
    ...root.querySelectorAll<HTMLElement>('[data-zui-tabs-trigger]'),
  ].indexOf(element)
}

// packages/zui/src/react/tabsContext.tsx
import {
  createContext,
  type RefObject,
  useContext,
  useSyncExternalStore,
} from 'react'
import type { TabsControllerApi, TabsSnapshot } from '../core/tabs'

export interface TabsContextValue {
  controller: TabsControllerApi
  rootRef: RefObject<HTMLDivElement | null>
}

export const TabsContext = createContext<TabsContextValue | null>(null)

export function useTabsContext() {
  const context = useContext(TabsContext)

  if (!context) {
    throw new Error('Tabs components must be used within <Tabs>.')
  }

  return context
}

export function useTabsSnapshot() {
  const { controller } = useTabsContext()

  return useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    controller.getSnapshot,
  ) as TabsSnapshot
}

export function getTabsTriggerOrder(
  root: HTMLDivElement | null,
  element: HTMLElement | null,
) {
  if (!root || !element) return 0

  return [...root.querySelectorAll<HTMLElement>('[data-zui-tabs-trigger]')].indexOf(
    element,
  )
}
