// packages/zui/src/vue/Textarea.vue
<template>
  <textarea :class="classes" v-bind="$attrs" />
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed } from 'vue'
import { textareaVariants } from '../shared/textareaVariants'

defineOptions({ inheritAttrs: false })

type TextareaVariantProps = VariantProps<typeof textareaVariants>

const props = defineProps<{
  class?: string
  shape?: TextareaVariantProps['shape']
}>()

const classes = computed(() =>
  textareaVariants({ className: props.class, shape: props.shape }),
)
</script>

// packages/zui/src/react/Textarea.tsx
import type { VariantProps } from 'cva'
import type { TextareaHTMLAttributes } from 'react'
import { textareaVariants } from '../shared/textareaVariants'

type TextareaVariantProps = VariantProps<typeof textareaVariants>

export type TextareaProps = TextareaHTMLAttributes<HTMLTextAreaElement> &
  TextareaVariantProps & {
    className?: string
  }

export function Textarea({ className, shape, ...props }: TextareaProps) {
  const classes = textareaVariants({ className, shape })
  return <textarea className={classes} {...props} />
}
