// src/solid/Textarea.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TextareaProps = JSX.TextareaHTMLAttributes<HTMLTextAreaElement> & {
	class?: string
}

export function Textarea(props: TextareaProps) {
	const [local, rest] = splitProps(props, ['class'])
	const classes = () => ['zui-textarea', local.class].filter(Boolean).join(' ')
	return <textarea class={classes()} {...rest} />
}

// packages/zui/src/react/Textarea.tsx
import type { TextareaHTMLAttributes } from 'react'

export type TextareaProps = TextareaHTMLAttributes<HTMLTextAreaElement> & {
  className?: string
}

export function Textarea({ className, ...props }: TextareaProps) {
  const classes = ['zui-textarea', className].filter(Boolean).join(' ')
  return <textarea className={classes} {...props} />
}
