// src/react/Code.tsx
import type { HTMLAttributes } from 'react'

export type CodeProps = HTMLAttributes<HTMLElement> & {
  className?: string
}

export function Code({ className, children, ...props }: CodeProps) {
  const classes = ['zui-code', className].filter(Boolean).join(' ')
  return (
    <code className={classes} {...props}>
      {children}
    </code>
  )
}

// packages/zui/src/solid/Code.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type CodeProps = JSX.HTMLAttributes<HTMLElement> & {
  class?: string
}

export function Code(props: CodeProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-code', local.class].filter(Boolean).join(' ')
  return (
    <code class={classes()} {...rest}>
      {local.children}
    </code>
  )
}
