// packages/zui/src/react/FieldGroup.tsx
import type { HTMLAttributes } from 'react'

export type FieldGroupProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldGroup({ className, children, ...props }: FieldGroupProps) {
  const classes = ['zui-field-group', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/solid/FieldGroup.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type FieldGroupProps = JSX.HTMLAttributes<HTMLDivElement> & {
  class?: string
}

export function FieldGroup(props: FieldGroupProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-field-group', local.class].filter(Boolean).join(' ')
  return (
    <div class={classes()} {...rest}>
      {local.children}
    </div>
  )
}
