// packages/zui/src/react/FieldSet.tsx
import type { HTMLAttributes } from 'react'

export type FieldSetProps = HTMLAttributes<HTMLFieldSetElement> & {
  className?: string
}

export function FieldSet({ className, children, ...props }: FieldSetProps) {
  const classes = ['zui-field-set', className].filter(Boolean).join(' ')
  return (
    <fieldset className={classes} {...props}>
      {children}
    </fieldset>
  )
}

// packages/zui/src/solid/FieldSet.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type FieldSetProps = JSX.HTMLAttributes<HTMLFieldSetElement> & {
  class?: string
}

export function FieldSet(props: FieldSetProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-field-set', local.class].filter(Boolean).join(' ')
  return (
    <fieldset class={classes()} {...rest}>
      {local.children}
    </fieldset>
  )
}
