// packages/zui/src/react/FieldLegend.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { fieldLegendVariants } from '../shared/fieldLegendVariants'

type FieldLegendVariantProps = VariantProps<typeof fieldLegendVariants>

export type FieldLegendProps = HTMLAttributes<HTMLLegendElement> &
  FieldLegendVariantProps & {
    className?: string
  }

export function FieldLegend({
  className,
  variant,
  children,
  ...props
}: FieldLegendProps) {
  const classes = fieldLegendVariants({
    className,
    variant,
  })
  return (
    <legend className={classes} {...props}>
      {children}
    </legend>
  )
}

// packages/zui/src/solid/FieldLegend.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'
import { fieldLegendVariants } from '../shared/fieldLegendVariants'

export type FieldLegendProps = JSX.HTMLAttributes<HTMLLegendElement> & {
  class?: string
  variant?: 'legend' | 'label'
}

export function FieldLegend(props: FieldLegendProps) {
  const [local, rest] = splitProps(props, ['class', 'variant', 'children'])
  const classes = () =>
    fieldLegendVariants({
      className: local.class,
      variant: local.variant,
    })
  return (
    <legend class={classes()} {...rest}>
      {local.children}
    </legend>
  )
}
