// packages/zui/src/react/FieldDescription.tsx
import type { HTMLAttributes } from 'react'

export type FieldDescriptionProps = HTMLAttributes<HTMLDivElement> & {
  className?: string
}

export function FieldDescription({
  className,
  children,
  ...props
}: FieldDescriptionProps) {
  const classes = ['zui-field-description', className].filter(Boolean).join(' ')
  return (
    <div className={classes} {...props}>
      {children}
    </div>
  )
}

// packages/zui/src/solid/FieldDescription.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type FieldDescriptionProps = JSX.HTMLAttributes<HTMLDivElement> & {
  class?: string
}

export function FieldDescription(props: FieldDescriptionProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () =>
    ['zui-field-description', local.class].filter(Boolean).join(' ')
  return (
    <div class={classes()} {...rest}>
      {local.children}
    </div>
  )
}
