// packages/zui/src/vue/MenuItem.vue
<template>
  <a
    v-if="href"
    v-bind="$attrs"
    ref="itemRef"
    :aria-disabled="snapshot.disabled || disabled ? 'true' : undefined"
    :class="classes"
    :data-disabled="snapshot.disabled || disabled ? 'true' : undefined"
    :data-highlighted="highlighted ? 'true' : undefined"
    :data-text-value="textValue"
    data-zui-menu-item=""
    :href="href"
    :id="itemId"
    role="menuitem"
    :tabindex="snapshot.open && highlighted ? 0 : -1"
    @click="handleClick"
    @focus="handleFocus"
    @pointerenter="handlePointerEnter"
  >
    <slot />
  </a>
  <button
    v-else
    v-bind="$attrs"
    ref="itemRef"
    :class="classes"
    :data-disabled="snapshot.disabled || disabled ? 'true' : undefined"
    :data-highlighted="highlighted ? 'true' : undefined"
    :data-text-value="textValue"
    data-zui-menu-item=""
    :disabled="snapshot.disabled || disabled"
    :id="itemId"
    role="menuitem"
    :tabindex="snapshot.open && highlighted ? 0 : -1"
    type="button"
    @click="handleClick"
    @focus="handleFocus"
    @pointerenter="handlePointerEnter"
  >
    <slot />
  </button>
</template>

<script setup lang="ts">
import type { VariantProps } from 'cva'
import { computed, onUnmounted, ref, watchEffect } from 'vue'
import { createMenuItemId } from '../core/menu'
import { buttonVariants } from '../shared/buttonVariants'
import { getMenuItemOrder, useMenuContext } from './menuContext'

defineOptions({ inheritAttrs: false })

type ButtonVariantProps = VariantProps<typeof buttonVariants>

const props = withDefaults(
  defineProps<{
    class?: string
    disabled?: boolean
    href?: string
    id?: string
    textValue?: string
    variant?: ButtonVariantProps['variant']
    color?: ButtonVariantProps['color']
    size?: ButtonVariantProps['size']
    shape?: ButtonVariantProps['shape']
    icon?: ButtonVariantProps['icon']
  }>(),
  {
    disabled: false,
    variant: 'ghost',
  },
)

const { controller, rootRef, snapshot } = useMenuContext()
const itemRef = ref<HTMLElement>()
const fallbackId = createMenuItemId(snapshot.value.rootId)
const itemId = computed(() => props.id ?? fallbackId)
const highlighted = computed(() => snapshot.value.highlightedItemId === itemId.value)
let unregister = () => {}

watchEffect(() => {
  unregister()
  unregister = controller.registerItem({
    disabled: props.disabled,
    element: itemRef.value ?? null,
    id: itemId.value,
    kind: props.href ? 'link' : 'button',
    order: getMenuItemOrder(rootRef.value, itemRef.value),
    textValue: props.textValue,
  })
})

onUnmounted(() => unregister())

const classes = computed(() =>
  buttonVariants({
    className: ['zui-menu-item', props.class].filter(Boolean).join(' '),
    color: props.color,
    icon: props.icon,
    shape: props.shape,
    size: props.size,
    variant: props.variant,
  }),
)

function handleClick(event: MouseEvent) {
  if (event.defaultPrevented) return
  const accepted = controller.selectItem(itemId.value)
  if (!accepted && (snapshot.value.disabled || props.disabled)) event.preventDefault()
}

function handleFocus() {
  controller.focusItem(itemId.value)
}

function handlePointerEnter() {
  controller.handleItemPointerEnter(itemId.value)
}
</script>

// packages/zui/src/solid/MenuItem.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { createEffect, createUniqueId, onCleanup, splitProps } from 'solid-js'
import { createMenuItemId } from '../core/menu'
import { buttonVariants } from '../shared/buttonVariants'
import { getMenuItemOrder, useMenuContext } from './menuContext'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type MenuItemProps = ButtonVariantProps &
  JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  JSX.AnchorHTMLAttributes<HTMLAnchorElement> & {
    class?: string
    disabled?: boolean
    href?: string
    id?: string
    textValue?: string
  }

export function MenuItem(props: MenuItemProps) {
  const generatedId = createUniqueId()
  const [local, rest] = splitProps(props, [
    'class',
    'color',
    'disabled',
    'href',
    'icon',
    'id',
    'onClick',
    'onFocus',
    'onPointerEnter',
    'shape',
    'size',
    'textValue',
    'variant',
  ])
  const { controller, rootRef, snapshot } = useMenuContext()
  const fallbackId = createMenuItemId(snapshot().rootId, `solid-${generatedId}`)
  const itemId = () => local.id ?? fallbackId
  let ref: HTMLElement | undefined

  createEffect(() => {
    const unregister = controller.registerItem({
      disabled: local.disabled ?? false,
      element: ref ?? null,
      id: itemId(),
      kind: local.href ? 'link' : 'button',
      order: getMenuItemOrder(rootRef(), ref),
      textValue: local.textValue,
    })
    onCleanup(unregister)
  })

  const highlighted = () => snapshot().highlightedItemId === itemId()
  const classes = () =>
    buttonVariants({
      className: ['zui-menu-item', local.class].filter(Boolean).join(' '),
      color: local.color,
      icon: local.icon,
      shape: local.shape,
      size: local.size,
      variant: local.variant ?? 'ghost',
    })

  return local.href ? (
    <a
      {...(rest as JSX.AnchorHTMLAttributes<HTMLAnchorElement>)}
      ref={ref as HTMLAnchorElement}
      aria-disabled={snapshot().disabled || local.disabled ? 'true' : undefined}
      class={classes()}
      data-disabled={snapshot().disabled || local.disabled ? 'true' : undefined}
      data-highlighted={highlighted() ? 'true' : undefined}
      data-text-value={local.textValue}
      data-zui-menu-item=""
      href={local.href}
      id={itemId()}
      onClick={(event) => {
        local.onClick?.(event)
        if (!event.defaultPrevented) {
          const accepted = controller.selectItem(itemId())
          if (!accepted && (snapshot().disabled || local.disabled))
            event.preventDefault()
        }
      }}
      onFocus={(event) => {
        local.onFocus?.(event)
        if (!event.defaultPrevented) controller.focusItem(itemId())
      }}
      onPointerEnter={(event) => {
        local.onPointerEnter?.(event)
        if (!event.defaultPrevented) controller.handleItemPointerEnter(itemId())
      }}
      role="menuitem"
      tabIndex={snapshot().open && highlighted() ? 0 : -1}
    />
  ) : (
    <button
      {...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
      ref={ref as HTMLButtonElement}
      class={classes()}
      data-disabled={snapshot().disabled || local.disabled ? 'true' : undefined}
      data-highlighted={highlighted() ? 'true' : undefined}
      data-text-value={local.textValue}
      data-zui-menu-item=""
      disabled={snapshot().disabled || local.disabled}
      id={itemId()}
      onClick={(event) => {
        local.onClick?.(event)
        if (!event.defaultPrevented) controller.selectItem(itemId())
      }}
      onFocus={(event) => {
        local.onFocus?.(event)
        if (!event.defaultPrevented) controller.focusItem(itemId())
      }}
      onPointerEnter={(event) => {
        local.onPointerEnter?.(event)
        if (!event.defaultPrevented) controller.handleItemPointerEnter(itemId())
      }}
      role="menuitem"
      tabIndex={snapshot().open && highlighted() ? 0 : -1}
      type="button"
    />
  )
}
