// packages/zui/src/svelte/MenuTrigger.svelte
<script lang="ts">
import type { VariantProps } from 'cva'
import type { Snippet } from 'svelte'
import type { HTMLButtonAttributes } from 'svelte/elements'
import { buttonVariants } from '../shared/buttonVariants'
import { getMenuContext } from './menuContext'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

type Props = HTMLButtonAttributes & {
  class?: string
  disabled?: boolean
  variant?: ButtonVariantProps['variant']
  color?: ButtonVariantProps['color']
  size?: ButtonVariantProps['size']
  shape?: ButtonVariantProps['shape']
  icon?: ButtonVariantProps['icon']
  children?: Snippet
}

let {
  class: className,
  disabled = false,
  variant = 'outline',
  color,
  size,
  shape,
  icon,
  children,
  onClick,
  onKeyDown,
  ...rest
}: Props = $props()

const { controller, getSnapshot } = getMenuContext()
let ref = $state<HTMLButtonElement | undefined>()

$effect(() => controller.registerTrigger({ disabled, element: ref ?? null, triggerId: getSnapshot().triggerId }))

const classes = $derived(
  buttonVariants({
    className: ['zui-menu-trigger', className].filter(Boolean).join(' '),
    color,
    icon,
    shape,
    size,
    variant,
  }),
)
</script>

<button
  {...rest}
  bind:this={ref}
  aria-controls={getSnapshot().contentId}
  aria-expanded={getSnapshot().open}
  aria-haspopup="menu"
  class={classes}
  data-disabled={getSnapshot().triggerDisabled ? 'true' : undefined}
  data-state={getSnapshot().open ? 'open' : 'closed'}
  data-zui-menu-trigger=""
  disabled={getSnapshot().disabled || disabled}
  id={getSnapshot().triggerId}
  on:click={(event) => {
    onClick?.(event)
    if (!event.defaultPrevented) controller.handleTriggerClick()
  }}
  on:keydown={(event) => {
    onKeyDown?.(event)
    if (!event.defaultPrevented) controller.handleTriggerKeydown(event)
  }}
  type="button"
>
  {@render children?.()}
</button>

// packages/zui/src/solid/MenuTrigger.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { createEffect, onCleanup, splitProps } from 'solid-js'
import { buttonVariants } from '../shared/buttonVariants'
import { useMenuContext } from './menuContext'

type ButtonVariantProps = VariantProps<typeof buttonVariants>

export type MenuTriggerProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  ButtonVariantProps

export function MenuTrigger(props: MenuTriggerProps) {
  const [local, rest] = splitProps(props, [
    'class',
    'disabled',
    'onClick',
    'onKeyDown',
    'variant',
    'color',
    'size',
    'shape',
    'icon',
  ])
  const { controller, snapshot } = useMenuContext()
  const triggerId = controller.getSnapshot().triggerId
  let ref: HTMLButtonElement | undefined

  createEffect(() => {
    const unregister = controller.registerTrigger({
      disabled: local.disabled ?? false,
      element: ref ?? null,
      triggerId,
    })
    onCleanup(unregister)
  })

  const classes = () =>
    buttonVariants({
      className: ['zui-menu-trigger', local.class].filter(Boolean).join(' '),
      color: local.color,
      icon: local.icon,
      shape: local.shape,
      size: local.size,
      variant: local.variant ?? 'outline',
    })

  return (
    <button
      {...rest}
      ref={ref}
      aria-controls={snapshot().contentId}
      aria-expanded={snapshot().open}
      aria-haspopup="menu"
      class={classes()}
      data-disabled={snapshot().triggerDisabled ? 'true' : undefined}
      data-state={snapshot().open ? 'open' : 'closed'}
      data-zui-menu-trigger=""
      disabled={snapshot().disabled || local.disabled}
      id={snapshot().triggerId}
      onClick={(event) => {
        local.onClick?.(event)
        if (!event.defaultPrevented) controller.handleTriggerClick()
      }}
      onKeyDown={(event) => {
        local.onKeyDown?.(event)
        if (!event.defaultPrevented) controller.handleTriggerKeydown(event)
      }}
      type="button"
    />
  )
}
