// packages/zui/src/react/Menu.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { useEffect, useId, useMemo, useRef, useSyncExternalStore } from 'react'
import {
  createMenuController,
  type MenuAlign,
  type MenuDirection,
  type MenuSide,
} from '../core/menu'
import { menuVariants } from '../shared/menuVariants'
import { MenuContext } from './menuContext'
import { useIsomorphicLayoutEffect } from './useIsomorphicLayoutEffect'

type MenuVariantProps = VariantProps<typeof menuVariants>

export type MenuProps = HTMLAttributes<HTMLDivElement> & {
  align?: MenuAlign
  defaultOpen?: boolean
  dir?: MenuDirection
  disabled?: boolean
  id?: string
  modal?: boolean
  onOpenChange?: (open: boolean) => void
  open?: boolean
  shape?: MenuVariantProps['shape']
  side?: MenuSide
}

export function Menu({
  align = 'start',
  children,
  className,
  defaultOpen,
  dir = 'ltr',
  disabled = false,
  id,
  modal = false,
  onOpenChange,
  open,
  shape,
  side = 'bottom',
  ...props
}: MenuProps) {
  const reactId = useId()
  const rootId = id ?? `zui-menu-${reactId.replace(/:/g, '')}`
  const rootRef = useRef<HTMLDivElement>(null)
  const controllerRef = useRef<ReturnType<typeof createMenuController> | null>(
    null,
  )

  if (!controllerRef.current) {
    controllerRef.current = createMenuController({
      align,
      defaultOpen,
      dir,
      disabled,
      id: rootId,
      modal,
      onOpenChange,
      open,
      side,
    })
  }

  const controller = controllerRef.current

  useIsomorphicLayoutEffect(() => {
    controller.setOptions({
      align,
      defaultOpen,
      dir,
      disabled,
      id: rootId,
      modal,
      onOpenChange,
      open,
      side,
    })
  }, [
    align,
    controller,
    defaultOpen,
    dir,
    disabled,
    modal,
    onOpenChange,
    open,
    rootId,
    side,
  ])

  useEffect(() => {
    const onPointerDown = (event: PointerEvent) => {
      controller.handleDocumentPointerDown(event.target)
    }

    document.addEventListener('pointerdown', onPointerDown)
    return () => document.removeEventListener('pointerdown', onPointerDown)
  }, [controller])

  const contextValue = useMemo(
    () => ({
      controller,
      rootRef,
    }),
    [controller],
  )

  const snapshot = useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    controller.getSnapshot,
  )

  return (
    <MenuContext.Provider value={contextValue}>
      <div
        {...props}
        ref={rootRef}
        className={menuVariants({ className, shape })}
        data-align={snapshot.align}
        data-disabled={snapshot.disabled ? 'true' : undefined}
        data-side={snapshot.side}
        data-state={snapshot.open ? 'open' : 'closed'}
        data-zui-menu-root=""
        id={snapshot.rootId}
      >
        {children}
      </div>
    </MenuContext.Provider>
  )
}

// packages/zui/src/solid/Menu.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import {
  createEffect,
  createSignal,
  createUniqueId,
  onCleanup,
  onMount,
  splitProps,
} from 'solid-js'
import {
  createMenuController,
  type MenuAlign,
  type MenuDirection,
  type MenuSide,
} from '../core/menu'
import { menuVariants } from '../shared/menuVariants'
import { MenuContext } from './menuContext'

type MenuVariantProps = VariantProps<typeof menuVariants>

export type MenuProps = JSX.HTMLAttributes<HTMLDivElement> & {
  align?: MenuAlign
  defaultOpen?: boolean
  dir?: MenuDirection
  disabled?: boolean
  id?: string
  modal?: boolean
  onOpenChange?: (open: boolean) => void
  open?: boolean
  shape?: MenuVariantProps['shape']
  side?: MenuSide
}

export function Menu(props: MenuProps) {
  const [local, rest] = splitProps(props, [
    'align',
    'children',
    'class',
    'defaultOpen',
    'dir',
    'disabled',
    'id',
    'modal',
    'onOpenChange',
    'open',
    'shape',
    'side',
  ])
  const generatedId = createUniqueId()
  const rootId = () => local.id ?? `zui-menu-${generatedId}`

  const controller = createMenuController({
    align: local.align,
    defaultOpen: local.defaultOpen,
    dir: local.dir,
    disabled: local.disabled,
    id: rootId(),
    modal: local.modal,
    onOpenChange: local.onOpenChange,
    open: local.open,
    side: local.side,
  })

  const [rootRef, setRootRef] = createSignal<HTMLDivElement>()
  const [snapshot, setSnapshot] = createSignal(controller.getSnapshot())
  const unsubscribe = controller.subscribe((next) => setSnapshot(next))

  createEffect(() => {
    controller.setOptions({
      align: local.align,
      defaultOpen: local.defaultOpen,
      dir: local.dir,
      disabled: local.disabled,
      id: rootId(),
      modal: local.modal,
      onOpenChange: local.onOpenChange,
      open: local.open,
      side: local.side,
    })
  })

  onMount(() => {
    const onPointerDown = (event: PointerEvent) =>
      controller.handleDocumentPointerDown(event.target)
    document.addEventListener('pointerdown', onPointerDown)
    onCleanup(() => {
      document.removeEventListener('pointerdown', onPointerDown)
    })
  })

  onCleanup(() => {
    unsubscribe()
  })

  return (
    <MenuContext.Provider value={{ controller, rootRef, snapshot }}>
      <div
        {...rest}
        ref={setRootRef}
        class={menuVariants({ class: local.class, shape: local.shape })}
        data-align={snapshot().align}
        data-disabled={snapshot().disabled ? 'true' : undefined}
        data-side={snapshot().side}
        data-state={snapshot().open ? 'open' : 'closed'}
        data-zui-menu-root=""
        id={snapshot().rootId}
      >
        {local.children}
      </div>
    </MenuContext.Provider>
  )
}
