// src/react/Table.tsx
import type { TableHTMLAttributes } from 'react'

export type TableProps = TableHTMLAttributes<HTMLTableElement> & {
  className?: string
}

export function Table({ className, children, ...props }: TableProps) {
  const classes = ['zui-table', className].filter(Boolean).join(' ')
  return <table className={classes} {...props}>{children}</table>
}

// packages/zui/src/solid/Table.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

export type TableProps = JSX.TableHTMLAttributes<HTMLTableElement> & {
  class?: string
}

export function Table(props: TableProps) {
  const [local, rest] = splitProps(props, ['class', 'children'])
  const classes = () => ['zui-table', local.class].filter(Boolean).join(' ')
  return (
    <table class={classes()} {...rest}>
      {local.children}
    </table>
  )
}
