// packages/zui/src/react/TabsTrigger.tsx
import type { VariantProps } from 'cva'
import type { ButtonHTMLAttributes } from 'react'
import { useEffect, useRef } from 'react'
import { createTabsContentId, createTabsTriggerId } from '../core/tabs'
import { tabsTriggerVariants } from '../shared/tabsVariants'
import {
  getTabsTriggerOrder,
  useTabsContext,
  useTabsSnapshot,
} from './tabsContext'

type TabsTriggerVariantProps = VariantProps<typeof tabsTriggerVariants>

export type TabsTriggerProps = ButtonHTMLAttributes<HTMLButtonElement> &
  TabsTriggerVariantProps & {
    value: string
  }

export function TabsTrigger({
  children,
  className,
  disabled = false,
  onBlur,
  onClick,
  onFocus,
  onKeyDown,
  value,
  variant,
  ...props
}: TabsTriggerProps) {
  const ref = useRef<HTMLButtonElement>(null)
  const { controller, rootRef } = useTabsContext()
  const snapshot = useTabsSnapshot()
  const isActive = snapshot.selectedValue === value
  const rootId = snapshot.rootId
  const triggerId = createTabsTriggerId(rootId, value)
  const panelId = createTabsContentId(rootId, value)
  const classes = tabsTriggerVariants({ className, variant })

  useEffect(() => {
    return controller.registerTrigger({
      disabled,
      element: ref.current,
      order: getTabsTriggerOrder(rootRef.current, ref.current),
      panelId,
      triggerId,
      value,
    })
  }, [controller, disabled, panelId, rootRef, triggerId, value])

  return (
    <button
      {...props}
      ref={ref}
      aria-controls={panelId}
      aria-selected={isActive}
      className={classes}
      data-disabled={disabled ? 'true' : undefined}
      data-orientation={snapshot.orientation}
      data-state={isActive ? 'active' : 'inactive'}
      data-value={value}
      data-zui-tabs-trigger=""
      disabled={disabled || snapshot.disabled}
      id={triggerId}
      onBlur={(event) => {
        onBlur?.(event)
        if (!event.defaultPrevented) controller.blurTrigger(value)
      }}
      onClick={(event) => {
        onClick?.(event)
        if (!event.defaultPrevented) controller.clickTrigger(value)
      }}
      onFocus={(event) => {
        onFocus?.(event)
        if (!event.defaultPrevented) controller.focusTrigger(value)
      }}
      onKeyDown={(event) => {
        onKeyDown?.(event)
        if (!event.defaultPrevented) {
          controller.handleTriggerKeydown(event.nativeEvent, value)
        }
      }}
      role="tab"
      tabIndex={isActive ? 0 : -1}
      type="button"
    >
      {children}
    </button>
  )
}

// packages/zui/src/solid/TabsTrigger.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import { createEffect, createMemo, onCleanup, splitProps } from 'solid-js'
import { createTabsContentId, createTabsTriggerId } from '../core/tabs'
import { tabsTriggerVariants } from '../shared/tabsVariants'
import { getTabsTriggerOrder, useTabsContext } from './tabsContext'

type TabsTriggerVariantProps = VariantProps<typeof tabsTriggerVariants>

export type TabsTriggerProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  TabsTriggerVariantProps & {
    value: string
  }

export function TabsTrigger(props: TabsTriggerProps) {
  const [local, rest] = splitProps(props, [
    'children',
    'class',
    'disabled',
    'onBlur',
    'onClick',
    'onFocus',
    'onKeyDown',
    'ref',
    'value',
    'variant',
  ])
  const { controller, rootRef, snapshot } = useTabsContext()
  let ref: HTMLButtonElement | undefined

  const classes = createMemo(() =>
    tabsTriggerVariants({ className: local.class, variant: local.variant }),
  )
  const isActive = createMemo(() => snapshot().selectedValue === local.value)
  const triggerId = createMemo(() => createTabsTriggerId(snapshot().rootId, local.value))
  const panelId = createMemo(() => createTabsContentId(snapshot().rootId, local.value))

  createEffect(() => {
    const unregister = controller.registerTrigger({
      disabled: !!local.disabled,
      element: ref ?? null,
      order: getTabsTriggerOrder(rootRef(), ref),
      panelId: panelId(),
      triggerId: triggerId(),
      value: local.value,
    })

    onCleanup(unregister)
  })

  function setRefs(element: HTMLButtonElement) {
    ref = element

    if (typeof local.ref === 'function') {
      local.ref(element)
      return
    }

    if (local.ref && typeof local.ref === 'object') {
      ;(local.ref as { current?: HTMLButtonElement }).current = element
    }
  }

  return (
    <button
      {...rest}
      ref={setRefs}
      aria-controls={panelId()}
      aria-selected={isActive()}
      class={classes()}
      data-disabled={local.disabled ? 'true' : undefined}
      data-orientation={snapshot().orientation}
      data-state={isActive() ? 'active' : 'inactive'}
      data-value={local.value}
      data-zui-tabs-trigger=""
      disabled={local.disabled || snapshot().disabled}
      id={triggerId()}
      onBlur={(event) => {
        local.onBlur?.(event)
        if (!event.defaultPrevented) controller.blurTrigger(local.value)
      }}
      onClick={(event) => {
        local.onClick?.(event)
        if (!event.defaultPrevented) controller.clickTrigger(local.value)
      }}
      onFocus={(event) => {
        local.onFocus?.(event)
        if (!event.defaultPrevented) controller.focusTrigger(local.value)
      }}
      onKeyDown={(event) => {
        local.onKeyDown?.(event)
        if (!event.defaultPrevented) {
          controller.handleTriggerKeydown(event, local.value)
        }
      }}
      role="tab"
      tabIndex={isActive() ? 0 : -1}
      type="button"
    >
      {local.children}
    </button>
  )
}
