// packages/zui/src/react/Tabs.tsx
import type { VariantProps } from 'cva'
import type { HTMLAttributes } from 'react'
import { useId, useMemo, useRef, useSyncExternalStore } from 'react'
import {
  createTabsController,
  type TabsActivationMode,
  type TabsDirection,
  type TabsOrientation,
} from '../core/tabs'
import { tabsVariants } from '../shared/tabsVariants'
import { TabsContext } from './tabsContext'
import { useIsomorphicLayoutEffect } from './useIsomorphicLayoutEffect'

type TabsVariantProps = VariantProps<typeof tabsVariants>

export type TabsProps = HTMLAttributes<HTMLDivElement> & {
  activationMode?: TabsActivationMode
  defaultValue?: string
  dir?: TabsDirection
  disabled?: boolean
  id?: string
  onValueChange?: (value: string) => void
  orientation?: TabsOrientation
  shape?: TabsVariantProps['shape']
  value?: string
}

export function Tabs({
  activationMode = 'auto',
  children,
  className,
  defaultValue,
  dir = 'ltr',
  disabled = false,
  id,
  onValueChange,
  orientation = 'horizontal',
  shape,
  value,
  ...props
}: TabsProps) {
  const reactId = useId()
  const rootId = id ?? `zui-tabs-${reactId.replace(/:/g, '')}`
  const rootRef = useRef<HTMLDivElement>(null)
  const controllerRef = useRef<ReturnType<typeof createTabsController> | null>(
    null,
  )

  if (!controllerRef.current) {
    controllerRef.current = createTabsController({
      activationMode,
      defaultValue,
      dir,
      disabled,
      id: rootId,
      onValueChange,
      orientation,
      value,
    })
  }

  const controller = controllerRef.current

  useIsomorphicLayoutEffect(() => {
    controller.setOptions({
      activationMode,
      defaultValue,
      dir,
      disabled,
      id: rootId,
      onValueChange,
      orientation,
      value,
    })
  }, [
    activationMode,
    controller,
    defaultValue,
    dir,
    disabled,
    onValueChange,
    orientation,
    rootId,
    value,
  ])

  const contextValue = useMemo(
    () => ({
      controller,
      rootRef,
    }),
    [controller],
  )

  const snapshot = useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    controller.getSnapshot,
  )
  const classes = tabsVariants({ className, shape })

  return (
    <TabsContext.Provider value={contextValue}>
      <div
        {...props}
        ref={rootRef}
        className={classes}
        data-disabled={snapshot.disabled ? 'true' : undefined}
        data-orientation={snapshot.orientation}
        data-zui-tabs-root=""
        id={snapshot.rootId}
      >
        {children}
      </div>
    </TabsContext.Provider>
  )
}

// packages/zui/src/solid/Tabs.tsx
import type { VariantProps } from 'cva'
import type { JSX } from 'solid-js'
import {
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
  splitProps,
} from 'solid-js'
import type {
  TabsActivationMode,
  TabsDirection,
  TabsOrientation,
} from '../core/tabs'
import { createTabsController } from '../core/tabs'
import { tabsVariants } from '../shared/tabsVariants'
import { TabsContext } from './tabsContext'

type TabsVariantProps = VariantProps<typeof tabsVariants>

export type TabsProps = JSX.HTMLAttributes<HTMLDivElement> & {
  activationMode?: TabsActivationMode
  defaultValue?: string
  dir?: TabsDirection
  disabled?: boolean
  id?: string
  onValueChange?: (value: string) => void
  orientation?: TabsOrientation
  shape?: TabsVariantProps['shape']
  value?: string
}

export function Tabs(props: TabsProps) {
  const [local, rest] = splitProps(props, [
    'activationMode',
    'children',
    'class',
    'defaultValue',
    'dir',
    'disabled',
    'id',
    'onValueChange',
    'orientation',
    'shape',
    'value',
  ])

  const controller = createTabsController({
    activationMode: local.activationMode,
    defaultValue: local.defaultValue,
    dir: local.dir,
    disabled: local.disabled,
    id: local.id,
    onValueChange: local.onValueChange,
    orientation: local.orientation,
    value: local.value,
  })

  const [rootRef, setRootRef] = createSignal<HTMLDivElement>()
  const [snapshot, setSnapshot] = createSignal(controller.getSnapshot())

  const unsubscribe = controller.subscribe(setSnapshot)
  onCleanup(unsubscribe)

  createEffect(() => {
    controller.setOptions({
      activationMode: local.activationMode,
      defaultValue: local.defaultValue,
      dir: local.dir,
      disabled: local.disabled,
      id: local.id,
      onValueChange: local.onValueChange,
      orientation: local.orientation,
      value: local.value,
    })
  })

  const classes = createMemo(() =>
    tabsVariants({ className: local.class, shape: local.shape }),
  )
  const contextValue = {
    controller,
    rootRef,
    snapshot,
  }

  return (
    <TabsContext.Provider value={contextValue}>
      <div
        {...rest}
        ref={setRootRef}
        class={classes()}
        data-disabled={snapshot().disabled ? 'true' : undefined}
        data-orientation={snapshot().orientation}
        data-zui-tabs-root=""
        id={snapshot().rootId}
      >
        {local.children}
      </div>
    </TabsContext.Provider>
  )
}
